// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/TeamWarp/warp-go-sdk/internal/apijson"
	"github.com/TeamWarp/warp-go-sdk/internal/apiquery"
	"github.com/TeamWarp/warp-go-sdk/internal/param"
	"github.com/TeamWarp/warp-go-sdk/internal/requestconfig"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// BenefitHealthPlanService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewBenefitHealthPlanService] method instead.
type BenefitHealthPlanService struct {
	Options []option.RequestOption
}

// NewBenefitHealthPlanService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewBenefitHealthPlanService(opts ...option.RequestOption) (r *BenefitHealthPlanService) {
	r = &BenefitHealthPlanService{}
	r.Options = opts
	return
}

// List company health plans. Defaults to active plans. A plan whose effectiveEndDate has elapsed is reported and filtered as terminated.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: BenefitHealthPlanListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*BenefitHealthPlanListResponse: Success
//
// Example:
//
//	healthPlan, err := client.Benefits.HealthPlans.List(context.Background(), sdk.BenefitHealthPlanListParams{
//		Limit:    sdk.F[string]("limit"),
//		Statuses: sdk.F[[]sdk.PublicHealthPlanStatus]([]sdk.PublicHealthPlanStatus{"active"}),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(healthPlan)
func (r *BenefitHealthPlanService) List(ctx context.Context, query BenefitHealthPlanListParams, opts ...option.RequestOption) (res *BenefitHealthPlanListResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/benefits/health_plans"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get a publicly visible company health plan by id.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: The tag of a company health plan.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PublicHealthPlan: A company health plan available through Warp.
//
// Example:
//
//	healthPlan, err := client.Benefits.HealthPlans.Get(context.Background(), "chpl_1234")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(healthPlan)
func (r *BenefitHealthPlanService) Get(ctx context.Context, id string, opts ...option.RequestOption) (res *PublicHealthPlan, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/benefits/health_plans/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type PublicHealthPlan struct {
	// The tag of a company health plan.
	ID string `json:"id" api:"required"`
	// The insurance carrier underwriting the health plan.
	Carrier PublicHealthPlanCarrier `json:"carrier" api:"required"`
	// The health coverage type.
	Type PublicHealthPlanType `json:"type" api:"required"`
	// The company-facing plan name.
	Name string `json:"name" api:"required"`
	// The carrier-assigned group number.
	GroupNumber string `json:"groupNumber" api:"required,nullable"`
	// The plan network structure.
	NetworkType        PublicHealthPlanNetworkType `json:"networkType" api:"required,nullable"`
	EffectiveStartDate string                      `json:"effectiveStartDate" api:"required"`
	EffectiveEndDate   string                      `json:"effectiveEndDate" api:"required,nullable"`
	// The public lifecycle status of a health plan.
	Status    PublicHealthPlanStatus `json:"status" api:"required"`
	CreatedAt string                 `json:"createdAt" api:"required"`
	UpdatedAt string                 `json:"updatedAt" api:"required"`
	JSON      publicHealthPlanJSON   `json:"-"`
}

// publicHealthPlanJSON contains the JSON metadata for the struct [PublicHealthPlan]
type publicHealthPlanJSON struct {
	ID                 apijson.Field
	Carrier            apijson.Field
	Type               apijson.Field
	Name               apijson.Field
	GroupNumber        apijson.Field
	NetworkType        apijson.Field
	EffectiveStartDate apijson.Field
	EffectiveEndDate   apijson.Field
	Status             apijson.Field
	CreatedAt          apijson.Field
	UpdatedAt          apijson.Field
	raw                string
	ExtraFields        map[string]apijson.Field
}

func (r *PublicHealthPlan) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicHealthPlanJSON) RawJSON() string {
	return r.raw
}

type PublicHealthPlanType string

const (
	PublicHealthPlanTypeMedical             PublicHealthPlanType = "medical"
	PublicHealthPlanTypeDental              PublicHealthPlanType = "dental"
	PublicHealthPlanTypeVision              PublicHealthPlanType = "vision"
	PublicHealthPlanTypeLife                PublicHealthPlanType = "life"
	PublicHealthPlanTypeShortTermDisability PublicHealthPlanType = "short_term_disability"
	PublicHealthPlanTypeLongTermDisability  PublicHealthPlanType = "long_term_disability"
)

func (r PublicHealthPlanType) IsKnown() bool {
	switch r {
	case PublicHealthPlanTypeMedical, PublicHealthPlanTypeDental, PublicHealthPlanTypeVision, PublicHealthPlanTypeLife, PublicHealthPlanTypeShortTermDisability, PublicHealthPlanTypeLongTermDisability:
		return true
	}
	return false
}

type PublicHealthPlanNetworkType string

const (
	PublicHealthPlanNetworkTypeHmo       PublicHealthPlanNetworkType = "hmo"
	PublicHealthPlanNetworkTypePpo       PublicHealthPlanNetworkType = "ppo"
	PublicHealthPlanNetworkTypeEpo       PublicHealthPlanNetworkType = "epo"
	PublicHealthPlanNetworkTypePos       PublicHealthPlanNetworkType = "pos"
	PublicHealthPlanNetworkTypeHdhp      PublicHealthPlanNetworkType = "hdhp"
	PublicHealthPlanNetworkTypeIndemnity PublicHealthPlanNetworkType = "indemnity"
)

func (r PublicHealthPlanNetworkType) IsKnown() bool {
	switch r {
	case PublicHealthPlanNetworkTypeHmo, PublicHealthPlanNetworkTypePpo, PublicHealthPlanNetworkTypeEpo, PublicHealthPlanNetworkTypePos, PublicHealthPlanNetworkTypeHdhp, PublicHealthPlanNetworkTypeIndemnity:
		return true
	}
	return false
}

type PublicHealthPlanCarrier struct {
	// The tag of a carrier.
	ID string `json:"id" api:"required"`
	// The carrier name.
	Name string                      `json:"name" api:"required"`
	JSON publicHealthPlanCarrierJSON `json:"-"`
}

// publicHealthPlanCarrierJSON contains the JSON metadata for the struct [PublicHealthPlanCarrier]
type publicHealthPlanCarrierJSON struct {
	ID          apijson.Field
	Name        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicHealthPlanCarrier) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicHealthPlanCarrierJSON) RawJSON() string {
	return r.raw
}

type PublicHealthPlanStatus string

const (
	PublicHealthPlanStatusActive     PublicHealthPlanStatus = "active"
	PublicHealthPlanStatusTerminated PublicHealthPlanStatus = "terminated"
)

func (r PublicHealthPlanStatus) IsKnown() bool {
	switch r {
	case PublicHealthPlanStatusActive, PublicHealthPlanStatusTerminated:
		return true
	}
	return false
}

type BenefitHealthPlanListParams struct {
	Limit    param.Field[string]                   `query:"limit" api:"required"`
	Statuses param.Field[[]PublicHealthPlanStatus] `query:"statuses" api:"required"`
	// The tag of a company health plan.
	AfterID param.Field[string] `query:"afterId"`
	// The tag of a company health plan.
	BeforeID   param.Field[string]                            `query:"beforeId"`
	CarrierIDs param.Field[[]string]                          `query:"carrierIds"`
	Types      param.Field[[]BenefitHealthPlanListParamsType] `query:"types"`
}

// URLQuery serializes [BenefitHealthPlanListParams]'s query parameters as `url.Values`.
func (r BenefitHealthPlanListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type BenefitHealthPlanListParamsType string

const (
	BenefitHealthPlanListParamsTypeMedical             BenefitHealthPlanListParamsType = "medical"
	BenefitHealthPlanListParamsTypeDental              BenefitHealthPlanListParamsType = "dental"
	BenefitHealthPlanListParamsTypeVision              BenefitHealthPlanListParamsType = "vision"
	BenefitHealthPlanListParamsTypeLife                BenefitHealthPlanListParamsType = "life"
	BenefitHealthPlanListParamsTypeShortTermDisability BenefitHealthPlanListParamsType = "short_term_disability"
	BenefitHealthPlanListParamsTypeLongTermDisability  BenefitHealthPlanListParamsType = "long_term_disability"
)

func (r BenefitHealthPlanListParamsType) IsKnown() bool {
	switch r {
	case BenefitHealthPlanListParamsTypeMedical, BenefitHealthPlanListParamsTypeDental, BenefitHealthPlanListParamsTypeVision, BenefitHealthPlanListParamsTypeLife, BenefitHealthPlanListParamsTypeShortTermDisability, BenefitHealthPlanListParamsTypeLongTermDisability:
		return true
	}
	return false
}

type BenefitHealthPlanListResponse struct {
	HasMore bool                              `json:"hasMore" api:"required"`
	Count   int64                             `json:"count" api:"required"`
	Data    []PublicHealthPlan                `json:"data" api:"required"`
	JSON    benefitHealthPlanListResponseJSON `json:"-"`
}

// benefitHealthPlanListResponseJSON contains the JSON metadata for the struct [BenefitHealthPlanListResponse]
type benefitHealthPlanListResponseJSON struct {
	HasMore     apijson.Field
	Count       apijson.Field
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *BenefitHealthPlanListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r benefitHealthPlanListResponseJSON) RawJSON() string {
	return r.raw
}
