// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/TeamWarp/warp-go-sdk/internal/apijson"
	"github.com/TeamWarp/warp-go-sdk/internal/apiquery"
	"github.com/TeamWarp/warp-go-sdk/internal/param"
	"github.com/TeamWarp/warp-go-sdk/internal/requestconfig"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// BenefitRetirementPlanService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewBenefitRetirementPlanService] method instead.
type BenefitRetirementPlanService struct {
	Options []option.RequestOption
}

// NewBenefitRetirementPlanService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewBenefitRetirementPlanService(opts ...option.RequestOption) (r *BenefitRetirementPlanService) {
	r = &BenefitRetirementPlanService{}
	r.Options = opts
	return
}

// List company retirement plans. Defaults to active plans. A plan whose effectiveEndDate has elapsed is reported and filtered as terminated.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: BenefitRetirementPlanListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*BenefitRetirementPlanListResponse: Success
//
// Example:
//
//	retirementPlan, err := client.Benefits.RetirementPlans.List(context.Background(), sdk.BenefitRetirementPlanListParams{
//		Limit:    sdk.F[string]("limit"),
//		Statuses: sdk.F[[]sdk.PublicRetirementPlanStatus]([]sdk.PublicRetirementPlanStatus{"active"}),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(retirementPlan)
func (r *BenefitRetirementPlanService) List(ctx context.Context, query BenefitRetirementPlanListParams, opts ...option.RequestOption) (res *BenefitRetirementPlanListResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/benefits/retirement_plans"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get a company retirement plan by id, regardless of status.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: The tag of a company retirement plan.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PublicRetirementPlan: A company retirement plan available through Warp.
//
// Example:
//
//	retirementPlan, err := client.Benefits.RetirementPlans.Get(context.Background(), "crpl_1234")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(retirementPlan)
func (r *BenefitRetirementPlanService) Get(ctx context.Context, id string, opts ...option.RequestOption) (res *PublicRetirementPlan, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/benefits/retirement_plans/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type PublicRetirementPlan struct {
	// The tag of a company retirement plan.
	ID string `json:"id" api:"required"`
	// The retirement plan type.
	Type PublicRetirementPlanType `json:"type" api:"required"`
	// The company-facing plan name.
	Name string `json:"name" api:"required"`
	// The system administering the plan. Manual plans are administered by the company
	// outside a connected provider.
	Provider           PublicRetirementPlanProvider `json:"provider" api:"required"`
	EffectiveStartDate string                       `json:"effectiveStartDate" api:"required"`
	EffectiveEndDate   string                       `json:"effectiveEndDate" api:"required,nullable"`
	// The public lifecycle status of a retirement plan.
	Status    PublicRetirementPlanStatus `json:"status" api:"required"`
	CreatedAt string                     `json:"createdAt" api:"required"`
	UpdatedAt string                     `json:"updatedAt" api:"required"`
	JSON      publicRetirementPlanJSON   `json:"-"`
}

// publicRetirementPlanJSON contains the JSON metadata for the struct [PublicRetirementPlan]
type publicRetirementPlanJSON struct {
	ID                 apijson.Field
	Type               apijson.Field
	Name               apijson.Field
	Provider           apijson.Field
	EffectiveStartDate apijson.Field
	EffectiveEndDate   apijson.Field
	Status             apijson.Field
	CreatedAt          apijson.Field
	UpdatedAt          apijson.Field
	raw                string
	ExtraFields        map[string]apijson.Field
}

func (r *PublicRetirementPlan) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicRetirementPlanJSON) RawJSON() string {
	return r.raw
}

type PublicRetirementPlanType string

const (
	PublicRetirementPlanType401k          PublicRetirementPlanType = "401k"
	PublicRetirementPlanTypeRoth401k      PublicRetirementPlanType = "roth_401k"
	PublicRetirementPlanType403b          PublicRetirementPlanType = "403b"
	PublicRetirementPlanTypeRoth403b      PublicRetirementPlanType = "roth_403b"
	PublicRetirementPlanType457           PublicRetirementPlanType = "457"
	PublicRetirementPlanTypeRoth457       PublicRetirementPlanType = "roth_457"
	PublicRetirementPlanTypeSimpleIra     PublicRetirementPlanType = "simple_ira"
	PublicRetirementPlanTypeRothSimpleIra PublicRetirementPlanType = "roth_simple_ira"
)

func (r PublicRetirementPlanType) IsKnown() bool {
	switch r {
	case PublicRetirementPlanType401k, PublicRetirementPlanTypeRoth401k, PublicRetirementPlanType403b, PublicRetirementPlanTypeRoth403b, PublicRetirementPlanType457, PublicRetirementPlanTypeRoth457, PublicRetirementPlanTypeSimpleIra, PublicRetirementPlanTypeRothSimpleIra:
		return true
	}
	return false
}

type PublicRetirementPlanProvider string

const (
	PublicRetirementPlanProviderManual        PublicRetirementPlanProvider = "manual"
	PublicRetirementPlanProviderHumanInterest PublicRetirementPlanProvider = "human_interest"
	PublicRetirementPlanProviderAccrue        PublicRetirementPlanProvider = "accrue"
)

func (r PublicRetirementPlanProvider) IsKnown() bool {
	switch r {
	case PublicRetirementPlanProviderManual, PublicRetirementPlanProviderHumanInterest, PublicRetirementPlanProviderAccrue:
		return true
	}
	return false
}

type PublicRetirementPlanStatus string

const (
	PublicRetirementPlanStatusActive     PublicRetirementPlanStatus = "active"
	PublicRetirementPlanStatusTerminated PublicRetirementPlanStatus = "terminated"
)

func (r PublicRetirementPlanStatus) IsKnown() bool {
	switch r {
	case PublicRetirementPlanStatusActive, PublicRetirementPlanStatusTerminated:
		return true
	}
	return false
}

type BenefitRetirementPlanListParams struct {
	Limit    param.Field[string]                       `query:"limit" api:"required"`
	Statuses param.Field[[]PublicRetirementPlanStatus] `query:"statuses" api:"required"`
	// The tag of a company retirement plan.
	AfterID param.Field[string] `query:"afterId"`
	// The tag of a company retirement plan.
	BeforeID param.Field[string]                                `query:"beforeId"`
	Types    param.Field[[]BenefitRetirementPlanListParamsType] `query:"types"`
}

// URLQuery serializes [BenefitRetirementPlanListParams]'s query parameters as `url.Values`.
func (r BenefitRetirementPlanListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type BenefitRetirementPlanListParamsType string

const (
	BenefitRetirementPlanListParamsType401k          BenefitRetirementPlanListParamsType = "401k"
	BenefitRetirementPlanListParamsTypeRoth401k      BenefitRetirementPlanListParamsType = "roth_401k"
	BenefitRetirementPlanListParamsType403b          BenefitRetirementPlanListParamsType = "403b"
	BenefitRetirementPlanListParamsTypeRoth403b      BenefitRetirementPlanListParamsType = "roth_403b"
	BenefitRetirementPlanListParamsType457           BenefitRetirementPlanListParamsType = "457"
	BenefitRetirementPlanListParamsTypeRoth457       BenefitRetirementPlanListParamsType = "roth_457"
	BenefitRetirementPlanListParamsTypeSimpleIra     BenefitRetirementPlanListParamsType = "simple_ira"
	BenefitRetirementPlanListParamsTypeRothSimpleIra BenefitRetirementPlanListParamsType = "roth_simple_ira"
)

func (r BenefitRetirementPlanListParamsType) IsKnown() bool {
	switch r {
	case BenefitRetirementPlanListParamsType401k, BenefitRetirementPlanListParamsTypeRoth401k, BenefitRetirementPlanListParamsType403b, BenefitRetirementPlanListParamsTypeRoth403b, BenefitRetirementPlanListParamsType457, BenefitRetirementPlanListParamsTypeRoth457, BenefitRetirementPlanListParamsTypeSimpleIra, BenefitRetirementPlanListParamsTypeRothSimpleIra:
		return true
	}
	return false
}

type BenefitRetirementPlanListResponse struct {
	HasMore bool                                  `json:"hasMore" api:"required"`
	Count   int64                                 `json:"count" api:"required"`
	Data    []PublicRetirementPlan                `json:"data" api:"required"`
	JSON    benefitRetirementPlanListResponseJSON `json:"-"`
}

// benefitRetirementPlanListResponseJSON contains the JSON metadata for the struct [BenefitRetirementPlanListResponse]
type benefitRetirementPlanListResponseJSON struct {
	HasMore     apijson.Field
	Count       apijson.Field
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *BenefitRetirementPlanListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r benefitRetirementPlanListResponseJSON) RawJSON() string {
	return r.raw
}
