// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"reflect"
	"slices"

	"github.com/tidwall/gjson"

	"github.com/TeamWarp/warp-go-sdk/internal/apijson"
	"github.com/TeamWarp/warp-go-sdk/internal/apiquery"
	"github.com/TeamWarp/warp-go-sdk/internal/param"
	"github.com/TeamWarp/warp-go-sdk/internal/requestconfig"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// BenefitDeductionService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewBenefitDeductionService] method instead.
type BenefitDeductionService struct {
	Options []option.RequestOption
}

// NewBenefitDeductionService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewBenefitDeductionService(opts ...option.RequestOption) (r *BenefitDeductionService) {
	r = &BenefitDeductionService{}
	r.Options = opts
	return
}

// List current payroll benefit deductions. Defaults to active deductions. A deduction whose effectiveEndDate has elapsed is reported and filtered as terminated.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: BenefitDeductionListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*BenefitDeductionListResponse: Success
//
// Example:
//
//	deduction, err := client.Benefits.Deductions.List(context.Background(), sdk.BenefitDeductionListParams{
//		Limit:    sdk.F[string]("limit"),
//		Statuses: sdk.F[[]sdk.PublicBenefitDeductionStatus]([]sdk.PublicBenefitDeductionStatus{"active"}),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(deduction)
func (r *BenefitDeductionService) List(ctx context.Context, query BenefitDeductionListParams, opts ...option.RequestOption) (res *BenefitDeductionListResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/benefits/deductions"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get the current version of a company benefit deduction by id.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: The version-group tag of a payroll benefit deduction. Stable across edits.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PublicBenefitDeduction: The current version of a stable payroll benefit deduction.
//
// Example:
//
//	deduction, err := client.Benefits.Deductions.Get(context.Background(), "pbdg_1234")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(deduction)
func (r *BenefitDeductionService) Get(ctx context.Context, id string, opts ...option.RequestOption) (res *PublicBenefitDeduction, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/benefits/deductions/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type PublicBenefitDeduction struct {
	// Stable identifier shared by every internal version of this deduction.
	ID string `json:"id" api:"required"`
	// Basic identifying information for a worker associated with another resource.
	Worker PublicWorkerReference `json:"worker" api:"required"`
	// The deduction name shown in payroll and benefits surfaces.
	Name string `json:"name" api:"required"`
	// The broad reporting category. The type field identifies the specific payroll
	// deduction.
	Category PublicBenefitDeductionCategory `json:"category" api:"required"`
	// The specific payroll deduction type within the broader category.
	Type PublicBenefitDeductionType `json:"type" api:"required"`
	// Whether the deduction recurs or applies once.
	Recurrence PublicBenefitDeductionRecurrence `json:"recurrence" api:"required"`
	// The associated benefit plan, or null for a planless payroll deduction.
	Plan PublicBenefitDeductionPlan2 `json:"plan" api:"required,nullable"`
	// How the employee and employer contributions are calculated.
	Calculation        PublicBenefitDeductionCalculation `json:"calculation" api:"required"`
	EffectiveStartDate string                            `json:"effectiveStartDate" api:"required"`
	EffectiveEndDate   string                            `json:"effectiveEndDate" api:"required,nullable"`
	// The public lifecycle status of the current deduction version.
	Status    PublicBenefitDeductionStatus `json:"status" api:"required"`
	CreatedAt string                       `json:"createdAt" api:"required"`
	UpdatedAt string                       `json:"updatedAt" api:"required"`
	JSON      publicBenefitDeductionJSON   `json:"-"`
}

// publicBenefitDeductionJSON contains the JSON metadata for the struct [PublicBenefitDeduction]
type publicBenefitDeductionJSON struct {
	ID                 apijson.Field
	Worker             apijson.Field
	Name               apijson.Field
	Category           apijson.Field
	Type               apijson.Field
	Recurrence         apijson.Field
	Plan               apijson.Field
	Calculation        apijson.Field
	EffectiveStartDate apijson.Field
	EffectiveEndDate   apijson.Field
	Status             apijson.Field
	CreatedAt          apijson.Field
	UpdatedAt          apijson.Field
	raw                string
	ExtraFields        map[string]apijson.Field
}

func (r *PublicBenefitDeduction) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicBenefitDeductionJSON) RawJSON() string {
	return r.raw
}

type PublicBenefitDeductionType string

const (
	PublicBenefitDeductionTypeMedical             PublicBenefitDeductionType = "medical"
	PublicBenefitDeductionTypeDental              PublicBenefitDeductionType = "dental"
	PublicBenefitDeductionTypeVision              PublicBenefitDeductionType = "vision"
	PublicBenefitDeductionTypeLife                PublicBenefitDeductionType = "life"
	PublicBenefitDeductionTypeShortTermDisability PublicBenefitDeductionType = "short_term_disability"
	PublicBenefitDeductionTypeLongTermDisability  PublicBenefitDeductionType = "long_term_disability"
	PublicBenefitDeductionType401k                PublicBenefitDeductionType = "401k"
	PublicBenefitDeductionTypeRoth401k            PublicBenefitDeductionType = "roth_401k"
	PublicBenefitDeductionType403b                PublicBenefitDeductionType = "403b"
	PublicBenefitDeductionTypeRoth403b            PublicBenefitDeductionType = "roth_403b"
	PublicBenefitDeductionType457                 PublicBenefitDeductionType = "457"
	PublicBenefitDeductionTypeRoth457             PublicBenefitDeductionType = "roth_457"
	PublicBenefitDeductionTypeHsa                 PublicBenefitDeductionType = "hsa"
	PublicBenefitDeductionTypeFsaMedical          PublicBenefitDeductionType = "fsa_medical"
	PublicBenefitDeductionTypeFsaDependentCare    PublicBenefitDeductionType = "fsa_dependent_care"
	PublicBenefitDeductionTypeTransit             PublicBenefitDeductionType = "transit"
	PublicBenefitDeductionTypeParking             PublicBenefitDeductionType = "parking"
	PublicBenefitDeductionTypeAccident            PublicBenefitDeductionType = "accident"
	PublicBenefitDeductionTypeCancer              PublicBenefitDeductionType = "cancer"
	PublicBenefitDeductionTypeCriticalIllness     PublicBenefitDeductionType = "critical_illness"
	PublicBenefitDeductionTypeHospital            PublicBenefitDeductionType = "hospital"
	PublicBenefitDeductionTypeMedicalOther        PublicBenefitDeductionType = "medical_other"
	PublicBenefitDeductionTypeSimpleIra           PublicBenefitDeductionType = "simple_ira"
	PublicBenefitDeductionTypeRothSimpleIra       PublicBenefitDeductionType = "roth_simple_ira"
	PublicBenefitDeductionTypeNqdc                PublicBenefitDeductionType = "nqdc"
	PublicBenefitDeductionTypeNontaxableFringe    PublicBenefitDeductionType = "nontaxable_fringe"
	PublicBenefitDeductionTypePucc                PublicBenefitDeductionType = "pucc"
	PublicBenefitDeductionTypeVoluntary           PublicBenefitDeductionType = "voluntary"
	PublicBenefitDeductionTypePostTax             PublicBenefitDeductionType = "post_tax"
	PublicBenefitDeductionTypeOther               PublicBenefitDeductionType = "other"
)

func (r PublicBenefitDeductionType) IsKnown() bool {
	switch r {
	case PublicBenefitDeductionTypeMedical, PublicBenefitDeductionTypeDental, PublicBenefitDeductionTypeVision, PublicBenefitDeductionTypeLife, PublicBenefitDeductionTypeShortTermDisability, PublicBenefitDeductionTypeLongTermDisability, PublicBenefitDeductionType401k, PublicBenefitDeductionTypeRoth401k, PublicBenefitDeductionType403b, PublicBenefitDeductionTypeRoth403b, PublicBenefitDeductionType457, PublicBenefitDeductionTypeRoth457, PublicBenefitDeductionTypeHsa, PublicBenefitDeductionTypeFsaMedical, PublicBenefitDeductionTypeFsaDependentCare, PublicBenefitDeductionTypeTransit, PublicBenefitDeductionTypeParking, PublicBenefitDeductionTypeAccident, PublicBenefitDeductionTypeCancer, PublicBenefitDeductionTypeCriticalIllness, PublicBenefitDeductionTypeHospital, PublicBenefitDeductionTypeMedicalOther, PublicBenefitDeductionTypeSimpleIra, PublicBenefitDeductionTypeRothSimpleIra, PublicBenefitDeductionTypeNqdc, PublicBenefitDeductionTypeNontaxableFringe, PublicBenefitDeductionTypePucc, PublicBenefitDeductionTypeVoluntary, PublicBenefitDeductionTypePostTax, PublicBenefitDeductionTypeOther:
		return true
	}
	return false
}

type PublicBenefitDeductionRecurrence string

const (
	PublicBenefitDeductionRecurrenceRecurring PublicBenefitDeductionRecurrence = "recurring"
	PublicBenefitDeductionRecurrenceOneTime   PublicBenefitDeductionRecurrence = "one_time"
)

func (r PublicBenefitDeductionRecurrence) IsKnown() bool {
	switch r {
	case PublicBenefitDeductionRecurrenceRecurring, PublicBenefitDeductionRecurrenceOneTime:
		return true
	}
	return false
}

type PublicWorkerReference struct {
	// The worker id.
	ID string `json:"id" api:"required"`
	// The worker first name.
	FirstName string `json:"firstName" api:"required"`
	// The worker last name.
	LastName string                    `json:"lastName" api:"required"`
	JSON     publicWorkerReferenceJSON `json:"-"`
}

// publicWorkerReferenceJSON contains the JSON metadata for the struct [PublicWorkerReference]
type publicWorkerReferenceJSON struct {
	ID          apijson.Field
	FirstName   apijson.Field
	LastName    apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicWorkerReference) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicWorkerReferenceJSON) RawJSON() string {
	return r.raw
}

type PublicBenefitDeductionCategory string

const (
	PublicBenefitDeductionCategoryHealth        PublicBenefitDeductionCategory = "health"
	PublicBenefitDeductionCategoryRetirement    PublicBenefitDeductionCategory = "retirement"
	PublicBenefitDeductionCategoryHealthSavings PublicBenefitDeductionCategory = "health_savings"
	PublicBenefitDeductionCategoryCommuter      PublicBenefitDeductionCategory = "commuter"
	PublicBenefitDeductionCategoryVoluntary     PublicBenefitDeductionCategory = "voluntary"
	PublicBenefitDeductionCategoryPostTax       PublicBenefitDeductionCategory = "post_tax"
	PublicBenefitDeductionCategoryOther         PublicBenefitDeductionCategory = "other"
)

func (r PublicBenefitDeductionCategory) IsKnown() bool {
	switch r {
	case PublicBenefitDeductionCategoryHealth, PublicBenefitDeductionCategoryRetirement, PublicBenefitDeductionCategoryHealthSavings, PublicBenefitDeductionCategoryCommuter, PublicBenefitDeductionCategoryVoluntary, PublicBenefitDeductionCategoryPostTax, PublicBenefitDeductionCategoryOther:
		return true
	}
	return false
}

type PublicBenefitDeductionStatus string

const (
	PublicBenefitDeductionStatusActive     PublicBenefitDeductionStatus = "active"
	PublicBenefitDeductionStatusPending    PublicBenefitDeductionStatus = "pending"
	PublicBenefitDeductionStatusSuspended  PublicBenefitDeductionStatus = "suspended"
	PublicBenefitDeductionStatusTerminated PublicBenefitDeductionStatus = "terminated"
)

func (r PublicBenefitDeductionStatus) IsKnown() bool {
	switch r {
	case PublicBenefitDeductionStatusActive, PublicBenefitDeductionStatusPending, PublicBenefitDeductionStatusSuspended, PublicBenefitDeductionStatusTerminated:
		return true
	}
	return false
}

type HealthPlanReference struct {
	Type HealthPlanReferenceType `json:"type" api:"required"`
	// The tag of a company health plan.
	ID string `json:"id" api:"required"`
	// The associated health plan name.
	Name string                  `json:"name" api:"required"`
	JSON healthPlanReferenceJSON `json:"-"`
}

// healthPlanReferenceJSON contains the JSON metadata for the struct [HealthPlanReference]
type healthPlanReferenceJSON struct {
	Type        apijson.Field
	ID          apijson.Field
	Name        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *HealthPlanReference) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r healthPlanReferenceJSON) RawJSON() string {
	return r.raw
}

type HealthPlanReferenceType string

const (
	HealthPlanReferenceTypeHealthPlan HealthPlanReferenceType = "health_plan"
)

func (r HealthPlanReferenceType) IsKnown() bool {
	switch r {
	case HealthPlanReferenceTypeHealthPlan:
		return true
	}
	return false
}

type RetirementPlanReference struct {
	Type RetirementPlanReferenceType `json:"type" api:"required"`
	// The tag of a company retirement plan.
	ID string `json:"id" api:"required"`
	// The associated retirement plan name.
	Name string                      `json:"name" api:"required"`
	JSON retirementPlanReferenceJSON `json:"-"`
}

// retirementPlanReferenceJSON contains the JSON metadata for the struct [RetirementPlanReference]
type retirementPlanReferenceJSON struct {
	Type        apijson.Field
	ID          apijson.Field
	Name        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *RetirementPlanReference) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r retirementPlanReferenceJSON) RawJSON() string {
	return r.raw
}

type RetirementPlanReferenceType string

const (
	RetirementPlanReferenceTypeRetirementPlan RetirementPlanReferenceType = "retirement_plan"
)

func (r RetirementPlanReferenceType) IsKnown() bool {
	switch r {
	case RetirementPlanReferenceTypeRetirementPlan:
		return true
	}
	return false
}

type FixedAmountBenefitCalculation struct {
	Type FixedAmountBenefitCalculationType `json:"type" api:"required"`
	// The fixed-amount expression frequency. Null for a one-time deduction.
	Frequency FixedAmountBenefitCalculationFrequency `json:"frequency" api:"required,nullable"`
	// A monetary amount with its currency and server-formatted display value.
	EmployeeContribution PublicMoneyAmount `json:"employeeContribution" api:"required"`
	// A monetary amount with its currency and server-formatted display value.
	EmployerContribution PublicMoneyAmount                 `json:"employerContribution" api:"required"`
	JSON                 fixedAmountBenefitCalculationJSON `json:"-"`
}

// fixedAmountBenefitCalculationJSON contains the JSON metadata for the struct [FixedAmountBenefitCalculation]
type fixedAmountBenefitCalculationJSON struct {
	Type                 apijson.Field
	Frequency            apijson.Field
	EmployeeContribution apijson.Field
	EmployerContribution apijson.Field
	raw                  string
	ExtraFields          map[string]apijson.Field
}

func (r *FixedAmountBenefitCalculation) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r fixedAmountBenefitCalculationJSON) RawJSON() string {
	return r.raw
}

type FixedAmountBenefitCalculationType string

const (
	FixedAmountBenefitCalculationTypeFixedAmount FixedAmountBenefitCalculationType = "fixed_amount"
)

func (r FixedAmountBenefitCalculationType) IsKnown() bool {
	switch r {
	case FixedAmountBenefitCalculationTypeFixedAmount:
		return true
	}
	return false
}

type FixedAmountBenefitCalculationFrequency string

const (
	FixedAmountBenefitCalculationFrequencyPerPaycheck FixedAmountBenefitCalculationFrequency = "per_paycheck"
	FixedAmountBenefitCalculationFrequencyMonthly     FixedAmountBenefitCalculationFrequency = "monthly"
)

func (r FixedAmountBenefitCalculationFrequency) IsKnown() bool {
	switch r {
	case FixedAmountBenefitCalculationFrequencyPerPaycheck, FixedAmountBenefitCalculationFrequencyMonthly:
		return true
	}
	return false
}

type PercentageBenefitCalculation struct {
	Type PercentageBenefitCalculationType `json:"type" api:"required"`
	// A contribution expressed as a percentage of eligible earnings.
	EmployeeContribution PercentageContribution `json:"employeeContribution" api:"required"`
	// A contribution expressed as a percentage of eligible earnings.
	EmployerContribution PercentageContribution           `json:"employerContribution" api:"required"`
	JSON                 percentageBenefitCalculationJSON `json:"-"`
}

// percentageBenefitCalculationJSON contains the JSON metadata for the struct [PercentageBenefitCalculation]
type percentageBenefitCalculationJSON struct {
	Type                 apijson.Field
	EmployeeContribution apijson.Field
	EmployerContribution apijson.Field
	raw                  string
	ExtraFields          map[string]apijson.Field
}

func (r *PercentageBenefitCalculation) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r percentageBenefitCalculationJSON) RawJSON() string {
	return r.raw
}

type PercentageBenefitCalculationType string

const (
	PercentageBenefitCalculationTypePercentage PercentageBenefitCalculationType = "percentage"
)

func (r PercentageBenefitCalculationType) IsKnown() bool {
	switch r {
	case PercentageBenefitCalculationTypePercentage:
		return true
	}
	return false
}

type PercentageContribution struct {
	Percentage interface{} `json:"percentage" api:"required"`
	// The server-formatted percentage, for example "3%".
	Display string                     `json:"display" api:"required"`
	JSON    percentageContributionJSON `json:"-"`
}

// percentageContributionJSON contains the JSON metadata for the struct [PercentageContribution]
type percentageContributionJSON struct {
	Percentage  apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PercentageContribution) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r percentageContributionJSON) RawJSON() string {
	return r.raw
}

type BenefitDeductionListParams struct {
	Limit    param.Field[string]                         `query:"limit" api:"required"`
	Statuses param.Field[[]PublicBenefitDeductionStatus] `query:"statuses" api:"required"`
	// The version-group tag of a payroll benefit deduction. Stable across edits.
	AfterID param.Field[string] `query:"afterId"`
	// The version-group tag of a payroll benefit deduction. Stable across edits.
	BeforeID          param.Field[string]                           `query:"beforeId"`
	Categories        param.Field[[]PublicBenefitDeductionCategory] `query:"categories"`
	HealthPlanIDs     param.Field[[]string]                         `query:"healthPlanIds"`
	RetirementPlanIDs param.Field[[]string]                         `query:"retirementPlanIds"`
	Types             param.Field[[]BenefitDeductionListParamsType] `query:"types"`
	WorkerIDs         param.Field[[]string]                         `query:"workerIds"`
}

// URLQuery serializes [BenefitDeductionListParams]'s query parameters as `url.Values`.
func (r BenefitDeductionListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type BenefitDeductionListParamsType string

const (
	BenefitDeductionListParamsTypeMedical             BenefitDeductionListParamsType = "medical"
	BenefitDeductionListParamsTypeDental              BenefitDeductionListParamsType = "dental"
	BenefitDeductionListParamsTypeVision              BenefitDeductionListParamsType = "vision"
	BenefitDeductionListParamsTypeLife                BenefitDeductionListParamsType = "life"
	BenefitDeductionListParamsTypeShortTermDisability BenefitDeductionListParamsType = "short_term_disability"
	BenefitDeductionListParamsTypeLongTermDisability  BenefitDeductionListParamsType = "long_term_disability"
	BenefitDeductionListParamsType401k                BenefitDeductionListParamsType = "401k"
	BenefitDeductionListParamsTypeRoth401k            BenefitDeductionListParamsType = "roth_401k"
	BenefitDeductionListParamsType403b                BenefitDeductionListParamsType = "403b"
	BenefitDeductionListParamsTypeRoth403b            BenefitDeductionListParamsType = "roth_403b"
	BenefitDeductionListParamsType457                 BenefitDeductionListParamsType = "457"
	BenefitDeductionListParamsTypeRoth457             BenefitDeductionListParamsType = "roth_457"
	BenefitDeductionListParamsTypeHsa                 BenefitDeductionListParamsType = "hsa"
	BenefitDeductionListParamsTypeFsaMedical          BenefitDeductionListParamsType = "fsa_medical"
	BenefitDeductionListParamsTypeFsaDependentCare    BenefitDeductionListParamsType = "fsa_dependent_care"
	BenefitDeductionListParamsTypeTransit             BenefitDeductionListParamsType = "transit"
	BenefitDeductionListParamsTypeParking             BenefitDeductionListParamsType = "parking"
	BenefitDeductionListParamsTypeAccident            BenefitDeductionListParamsType = "accident"
	BenefitDeductionListParamsTypeCancer              BenefitDeductionListParamsType = "cancer"
	BenefitDeductionListParamsTypeCriticalIllness     BenefitDeductionListParamsType = "critical_illness"
	BenefitDeductionListParamsTypeHospital            BenefitDeductionListParamsType = "hospital"
	BenefitDeductionListParamsTypeMedicalOther        BenefitDeductionListParamsType = "medical_other"
	BenefitDeductionListParamsTypeSimpleIra           BenefitDeductionListParamsType = "simple_ira"
	BenefitDeductionListParamsTypeRothSimpleIra       BenefitDeductionListParamsType = "roth_simple_ira"
	BenefitDeductionListParamsTypeNqdc                BenefitDeductionListParamsType = "nqdc"
	BenefitDeductionListParamsTypeNontaxableFringe    BenefitDeductionListParamsType = "nontaxable_fringe"
	BenefitDeductionListParamsTypePucc                BenefitDeductionListParamsType = "pucc"
	BenefitDeductionListParamsTypeVoluntary           BenefitDeductionListParamsType = "voluntary"
	BenefitDeductionListParamsTypePostTax             BenefitDeductionListParamsType = "post_tax"
	BenefitDeductionListParamsTypeOther               BenefitDeductionListParamsType = "other"
)

func (r BenefitDeductionListParamsType) IsKnown() bool {
	switch r {
	case BenefitDeductionListParamsTypeMedical, BenefitDeductionListParamsTypeDental, BenefitDeductionListParamsTypeVision, BenefitDeductionListParamsTypeLife, BenefitDeductionListParamsTypeShortTermDisability, BenefitDeductionListParamsTypeLongTermDisability, BenefitDeductionListParamsType401k, BenefitDeductionListParamsTypeRoth401k, BenefitDeductionListParamsType403b, BenefitDeductionListParamsTypeRoth403b, BenefitDeductionListParamsType457, BenefitDeductionListParamsTypeRoth457, BenefitDeductionListParamsTypeHsa, BenefitDeductionListParamsTypeFsaMedical, BenefitDeductionListParamsTypeFsaDependentCare, BenefitDeductionListParamsTypeTransit, BenefitDeductionListParamsTypeParking, BenefitDeductionListParamsTypeAccident, BenefitDeductionListParamsTypeCancer, BenefitDeductionListParamsTypeCriticalIllness, BenefitDeductionListParamsTypeHospital, BenefitDeductionListParamsTypeMedicalOther, BenefitDeductionListParamsTypeSimpleIra, BenefitDeductionListParamsTypeRothSimpleIra, BenefitDeductionListParamsTypeNqdc, BenefitDeductionListParamsTypeNontaxableFringe, BenefitDeductionListParamsTypePucc, BenefitDeductionListParamsTypeVoluntary, BenefitDeductionListParamsTypePostTax, BenefitDeductionListParamsTypeOther:
		return true
	}
	return false
}

type PublicBenefitDeductionCalculation struct {
	Type PublicBenefitDeductionCalculationType `json:"type" api:"required"`
	// A monetary amount with its currency and server-formatted display value.
	EmployeeContribution interface{} `json:"employeeContribution" api:"required"`
	// A monetary amount with its currency and server-formatted display value.
	EmployerContribution interface{} `json:"employerContribution" api:"required"`
	// The fixed-amount expression frequency. Null for a one-time deduction.
	Frequency PublicBenefitDeductionCalculationFrequency `json:"frequency" api:"nullable"`
	JSON      publicBenefitDeductionCalculationJSON      `json:"-"`
	union     PublicBenefitDeductionCalculationUnion
}

// publicBenefitDeductionCalculationJSON contains the JSON metadata for the struct [PublicBenefitDeductionCalculation]
type publicBenefitDeductionCalculationJSON struct {
	Type                 apijson.Field
	EmployeeContribution apijson.Field
	EmployerContribution apijson.Field
	Frequency            apijson.Field
	raw                  string
	ExtraFields          map[string]apijson.Field
}

func (r publicBenefitDeductionCalculationJSON) RawJSON() string {
	return r.raw
}

func (r *PublicBenefitDeductionCalculation) UnmarshalJSON(data []byte) (err error) {
	*r = PublicBenefitDeductionCalculation{}
	err = apijson.UnmarshalRoot(data, &r.union)
	if err != nil {
		return err
	}
	return apijson.Port(r.union, &r)
}

func (r PublicBenefitDeductionCalculation) AsUnion() PublicBenefitDeductionCalculationUnion {
	return r.union
}

type BenefitDeductionListResponse struct {
	HasMore bool                             `json:"hasMore" api:"required"`
	Count   int64                            `json:"count" api:"required"`
	Data    []PublicBenefitDeduction         `json:"data" api:"required"`
	JSON    benefitDeductionListResponseJSON `json:"-"`
}

// benefitDeductionListResponseJSON contains the JSON metadata for the struct [BenefitDeductionListResponse]
type benefitDeductionListResponseJSON struct {
	HasMore     apijson.Field
	Count       apijson.Field
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *BenefitDeductionListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r benefitDeductionListResponseJSON) RawJSON() string {
	return r.raw
}

type PublicBenefitDeductionPlan2 struct {
	Type PublicBenefitDeductionPlan2Type `json:"type" api:"required"`
	// The tag of a company health plan.
	ID string `json:"id" api:"required"`
	// The associated health plan name.
	Name  string                          `json:"name" api:"required"`
	JSON  publicBenefitDeductionPlan2JSON `json:"-"`
	union PublicBenefitDeductionPlan2Union
}

// publicBenefitDeductionPlan2JSON contains the JSON metadata for the struct [PublicBenefitDeductionPlan2]
type publicBenefitDeductionPlan2JSON struct {
	Type        apijson.Field
	ID          apijson.Field
	Name        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r publicBenefitDeductionPlan2JSON) RawJSON() string {
	return r.raw
}

func (r *PublicBenefitDeductionPlan2) UnmarshalJSON(data []byte) (err error) {
	*r = PublicBenefitDeductionPlan2{}
	err = apijson.UnmarshalRoot(data, &r.union)
	if err != nil {
		return err
	}
	return apijson.Port(r.union, &r)
}

func (r PublicBenefitDeductionPlan2) AsUnion() PublicBenefitDeductionPlan2Union {
	return r.union
}

type PublicBenefitDeductionCalculationUnion interface {
	implementsPublicBenefitDeductionCalculation()
}

func init() {
	apijson.RegisterUnion(
		reflect.TypeOf((*PublicBenefitDeductionCalculationUnion)(nil)).Elem(),
		"type",
		apijson.UnionVariant{
			TypeFilter:         gjson.JSON,
			Type:               reflect.TypeOf(FixedAmountBenefitCalculation{}),
			DiscriminatorValue: "fixed_amount",
		},
		apijson.UnionVariant{
			TypeFilter:         gjson.JSON,
			Type:               reflect.TypeOf(PercentageBenefitCalculation{}),
			DiscriminatorValue: "percentage",
		},
	)
}

type PublicBenefitDeductionCalculationType string

const (
	PublicBenefitDeductionCalculationTypeFixedAmount PublicBenefitDeductionCalculationType = "fixed_amount"
	PublicBenefitDeductionCalculationTypePercentage  PublicBenefitDeductionCalculationType = "percentage"
)

func (r PublicBenefitDeductionCalculationType) IsKnown() bool {
	switch r {
	case PublicBenefitDeductionCalculationTypeFixedAmount, PublicBenefitDeductionCalculationTypePercentage:
		return true
	}
	return false
}

type PublicBenefitDeductionCalculationFrequency string

const (
	PublicBenefitDeductionCalculationFrequencyPerPaycheck PublicBenefitDeductionCalculationFrequency = "per_paycheck"
	PublicBenefitDeductionCalculationFrequencyMonthly     PublicBenefitDeductionCalculationFrequency = "monthly"
)

func (r PublicBenefitDeductionCalculationFrequency) IsKnown() bool {
	switch r {
	case PublicBenefitDeductionCalculationFrequencyPerPaycheck, PublicBenefitDeductionCalculationFrequencyMonthly:
		return true
	}
	return false
}

type PublicBenefitDeductionPlan2Union interface {
	implementsPublicBenefitDeductionPlan2()
}

func init() {
	apijson.RegisterUnion(
		reflect.TypeOf((*PublicBenefitDeductionPlan2Union)(nil)).Elem(),
		"type",
		apijson.UnionVariant{
			TypeFilter:         gjson.JSON,
			Type:               reflect.TypeOf(HealthPlanReference{}),
			DiscriminatorValue: "health_plan",
		},
		apijson.UnionVariant{
			TypeFilter:         gjson.JSON,
			Type:               reflect.TypeOf(RetirementPlanReference{}),
			DiscriminatorValue: "retirement_plan",
		},
	)
}

type PublicBenefitDeductionPlan2Type string

const (
	PublicBenefitDeductionPlan2TypeHealthPlan     PublicBenefitDeductionPlan2Type = "health_plan"
	PublicBenefitDeductionPlan2TypeRetirementPlan PublicBenefitDeductionPlan2Type = "retirement_plan"
)

func (r PublicBenefitDeductionPlan2Type) IsKnown() bool {
	switch r {
	case PublicBenefitDeductionPlan2TypeHealthPlan, PublicBenefitDeductionPlan2TypeRetirementPlan:
		return true
	}
	return false
}

func (r FixedAmountBenefitCalculation) implementsPublicBenefitDeductionCalculation() {}

func (r PercentageBenefitCalculation) implementsPublicBenefitDeductionCalculation() {}

func (r HealthPlanReference) implementsPublicBenefitDeductionPlan2() {}

func (r RetirementPlanReference) implementsPublicBenefitDeductionPlan2() {}
