// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"context"
	"net/http"
	"os"
	"slices"
	"strings"

	"github.com/TeamWarp/warp-go-sdk/internal/requestconfig"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// Client creates a struct with services and top level methods that help with
// interacting with the warp API. You should not instantiate this client
// directly, and instead use the [NewClient] method instead.
type Client struct {
	Options      []option.RequestOption
	Benefits     *BenefitService
	CustomFields *CustomFieldService
	Departments  *DepartmentService
	Levels       *LevelService
	Offers       *OfferService
	PayRates     *PayRateService
	Payroll      *PayrollService
	TimeOff      *TimeOffService
	Workers      *WorkerService
	Workplaces   *WorkplaceService
	Webhooks     *WebhookService
}

// DefaultClientOptions read from the environment. This should be used to initialize
// new clients.
func DefaultClientOptions() []option.RequestOption {
	defaults := []option.RequestOption{option.WithHTTPClient(defaultHTTPClient()), option.WithEnvironmentProduction()}
	if o, ok := os.LookupEnv("WARP_BASE_URL"); ok {
		defaults = append(defaults, option.WithBaseURL(o))
	}
	if o, ok := os.LookupEnv("WARP_API_KEY"); ok {
		defaults = append(defaults, option.WithAPIKey(o))
	}
	if o, ok := os.LookupEnv("WARP_WEBHOOK_SECRET"); ok && o != "" {
		defaults = append(defaults, option.WithWebhookSecret(o))
	}
	if o, ok := os.LookupEnv("WARP_CUSTOM_HEADERS"); ok {
		for _, line := range strings.Split(o, "\n") {
			colon := strings.Index(line, ":")
			if colon >= 0 {
				defaults = append(defaults, option.WithHeader(strings.TrimSpace(line[:colon]), strings.TrimSpace(line[colon+1:])))
			}
		}
	}
	return defaults
}

// NewClient generates a new client with the default option read from the
// environment. The option passed in as arguments are applied after these default
// arguments, and all option will be passed down to the services and requests that
// this client makes.
func NewClient(opts ...option.RequestOption) (r *Client) {
	opts = append(DefaultClientOptions(), opts...)

	r = &Client{Options: opts}

	r.Benefits = NewBenefitService(opts...)
	r.CustomFields = NewCustomFieldService(opts...)
	r.Departments = NewDepartmentService(opts...)
	r.Levels = NewLevelService(opts...)
	r.Offers = NewOfferService(opts...)
	r.PayRates = NewPayRateService(opts...)
	r.Payroll = NewPayrollService(opts...)
	r.TimeOff = NewTimeOffService(opts...)
	r.Workers = NewWorkerService(opts...)
	r.Workplaces = NewWorkplaceService(opts...)
	r.Webhooks = NewWebhookService(opts...)

	return
}

// Execute makes a request with the given context, method, URL, request params,
// response, and request options.
func (r *Client) Execute(ctx context.Context, method string, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	opts = slices.Concat(r.Options, opts)
	return requestconfig.ExecuteNewRequest(ctx, method, path, params, res, opts...)
}

// Get makes a GET request with the given URL, params, and optionally
// deserializes to a response. See [Execute] documentation on the params and response.
func (r *Client) Get(ctx context.Context, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	return r.Execute(ctx, http.MethodGet, path, params, res, opts...)
}

// Post makes a POST request with the given URL, params, and optionally
// deserializes to a response. See [Execute] documentation on the params and response.
func (r *Client) Post(ctx context.Context, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	return r.Execute(ctx, http.MethodPost, path, params, res, opts...)
}

// Put makes a PUT request with the given URL, params, and optionally
// deserializes to a response. See [Execute] documentation on the params and response.
func (r *Client) Put(ctx context.Context, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	return r.Execute(ctx, http.MethodPut, path, params, res, opts...)
}

// Patch makes a PATCH request with the given URL, params, and optionally
// deserializes to a response. See [Execute] documentation on the params and response.
func (r *Client) Patch(ctx context.Context, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	return r.Execute(ctx, http.MethodPatch, path, params, res, opts...)
}

// Delete makes a DELETE request with the given URL, params, and optionally
// deserializes to a response. See [Execute] documentation on the params and response.
func (r *Client) Delete(ctx context.Context, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	return r.Execute(ctx, http.MethodDelete, path, params, res, opts...)
}
