// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/TeamWarp/warp-go-sdk/internal/apijson"
	"github.com/TeamWarp/warp-go-sdk/internal/apiquery"
	"github.com/TeamWarp/warp-go-sdk/internal/param"
	"github.com/TeamWarp/warp-go-sdk/internal/requestconfig"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// DepartmentService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewDepartmentService] method instead.
type DepartmentService struct {
	Options []option.RequestOption
}

// NewDepartmentService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewDepartmentService(opts ...option.RequestOption) (r *DepartmentService) {
	r = &DepartmentService{}
	r.Options = opts
	return
}

// List all departments for your company.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: DepartmentListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*DepartmentListResponse: Success
//
// Example:
//
//	department, err := client.Departments.List(context.Background(), sdk.DepartmentListParams{
//		Limit: sdk.F[string]("limit"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(department)
func (r *DepartmentService) List(ctx context.Context, query DepartmentListParams, opts ...option.RequestOption) (res *DepartmentListResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/departments"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Create a new department.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: DepartmentNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*DepartmentNewResponse: Success
//
// Example:
//
//	department, err := client.Departments.New(context.Background(), sdk.DepartmentNewParams{
//		Name: sdk.F[string]("x"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(department)
func (r *DepartmentService) New(ctx context.Context, body DepartmentNewParams, opts ...option.RequestOption) (res *DepartmentNewResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/departments"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Update an existing department.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: The unique public id of the department
//	body: DepartmentUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*DepartmentUpdateResponse: Success
//
// Example:
//
//	department, err := client.Departments.Update(context.Background(), "dpt_1234", sdk.DepartmentUpdateParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(department)
func (r *DepartmentService) Update(ctx context.Context, id string, body DepartmentUpdateParams, opts ...option.RequestOption) (res *DepartmentUpdateResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/departments/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

type DepartmentListParams struct {
	Limit param.Field[string] `query:"limit" api:"required"`
	// The unique public id of the department
	AfterID param.Field[string] `query:"afterId"`
	// The unique public id of the department
	BeforeID param.Field[string] `query:"beforeId"`
}

// URLQuery serializes [DepartmentListParams]'s query parameters as `url.Values`.
func (r DepartmentListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type DepartmentNewParams struct {
	Name param.Field[string] `json:"name" api:"required"`
}

func (r DepartmentNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type DepartmentUpdateParams struct {
	Name param.Field[string] `json:"name"`
}

func (r DepartmentUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type DepartmentListResponse struct {
	HasMore bool                         `json:"hasMore" api:"required"`
	Count   int64                        `json:"count" api:"required"`
	Data    []DepartmentListResponseData `json:"data" api:"required"`
	JSON    departmentListResponseJSON   `json:"-"`
}

// departmentListResponseJSON contains the JSON metadata for the struct [DepartmentListResponse]
type departmentListResponseJSON struct {
	HasMore     apijson.Field
	Count       apijson.Field
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *DepartmentListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r departmentListResponseJSON) RawJSON() string {
	return r.raw
}

type DepartmentNewResponse struct {
	// The unique public id of the department
	ID        string                    `json:"id" api:"required"`
	Name      string                    `json:"name" api:"required"`
	CreatedAt string                    `json:"createdAt" api:"required"`
	JSON      departmentNewResponseJSON `json:"-"`
}

// departmentNewResponseJSON contains the JSON metadata for the struct [DepartmentNewResponse]
type departmentNewResponseJSON struct {
	ID          apijson.Field
	Name        apijson.Field
	CreatedAt   apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *DepartmentNewResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r departmentNewResponseJSON) RawJSON() string {
	return r.raw
}

type DepartmentUpdateResponse struct {
	// The unique public id of the department
	ID        string                       `json:"id" api:"required"`
	Name      string                       `json:"name" api:"required"`
	CreatedAt string                       `json:"createdAt" api:"required"`
	JSON      departmentUpdateResponseJSON `json:"-"`
}

// departmentUpdateResponseJSON contains the JSON metadata for the struct [DepartmentUpdateResponse]
type departmentUpdateResponseJSON struct {
	ID          apijson.Field
	Name        apijson.Field
	CreatedAt   apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *DepartmentUpdateResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r departmentUpdateResponseJSON) RawJSON() string {
	return r.raw
}

type DepartmentListResponseData struct {
	// The unique public id of the department
	ID        string                         `json:"id" api:"required"`
	Name      string                         `json:"name" api:"required"`
	CreatedAt string                         `json:"createdAt" api:"required"`
	JSON      departmentListResponseDataJSON `json:"-"`
}

// departmentListResponseDataJSON contains the JSON metadata for the struct [DepartmentListResponseData]
type departmentListResponseDataJSON struct {
	ID          apijson.Field
	Name        apijson.Field
	CreatedAt   apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *DepartmentListResponseData) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r departmentListResponseDataJSON) RawJSON() string {
	return r.raw
}
