// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/TeamWarp/warp-go-sdk/internal/apijson"
	"github.com/TeamWarp/warp-go-sdk/internal/apiquery"
	"github.com/TeamWarp/warp-go-sdk/internal/param"
	"github.com/TeamWarp/warp-go-sdk/internal/requestconfig"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// I9VerificationService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewI9VerificationService] method instead.
type I9VerificationService struct {
	Options []option.RequestOption
}

// NewI9VerificationService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewI9VerificationService(opts ...option.RequestOption) (r *I9VerificationService) {
	r = &I9VerificationService{}
	r.Options = opts
	return
}

// List current and retained company I-9 verifications in all workflow states, newest first. Requires workers:compliance read access. Filters combine with AND across parameters and OR within each array. Count covers all matches before pagination. Use either afterId or beforeId; a missing or filter-mismatched cursor returns 400, so restart pagination if a filtered cursor changes state. Only verifications linked to a canonical company worker are returned.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: I9VerificationListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*I9VerificationListResponse: Success
//
// Example:
//
//	i9Verification, err := client.I9Verifications.List(context.Background(), sdk.I9VerificationListParams{
//		Limit: sdk.F[string]("limit"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(i9Verification)
func (r *I9VerificationService) List(ctx context.Context, query I9VerificationListParams, opts ...option.RequestOption) (res *I9VerificationListResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/i9-verifications"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get a current or retained I-9 verification by its i9v_ ID. Requires workers:compliance read access. Returns the same metadata as the list endpoint. Missing verifications and verifications outside the company or without a canonical worker return 404.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: The tag of the i9 verification.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*I9VerificationGetResponse: I-9 workflow metadata without document contents, identity details, or file links.
//
// Example:
//
//	i9Verification, err := client.I9Verifications.Get(context.Background(), "i9v_1234")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(i9Verification)
func (r *I9VerificationService) Get(ctx context.Context, id string, opts ...option.RequestOption) (res *I9VerificationGetResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/i9-verifications/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type PublicI9Verification struct {
	// The tag of the i9 verification.
	ID string `json:"id" api:"required"`
	// The id of the worker.
	WorkerID       string                     `json:"workerId" api:"required"`
	Status         PublicI9VerificationStatus `json:"status" api:"required"`
	StartDate      string                     `json:"startDate" api:"required"`
	VerifiedAt     time.Time                  `json:"verifiedAt" api:"required,nullable" format:"date-time"`
	RetentionUntil string                     `json:"retentionUntil" api:"required,nullable"`
	DueDate        string                     `json:"dueDate" api:"required,nullable"`
	JSON           publicI9VerificationJSON   `json:"-"`
}

// publicI9VerificationJSON contains the JSON metadata for the struct [PublicI9Verification]
type publicI9VerificationJSON struct {
	ID             apijson.Field
	WorkerID       apijson.Field
	Status         apijson.Field
	StartDate      apijson.Field
	VerifiedAt     apijson.Field
	RetentionUntil apijson.Field
	DueDate        apijson.Field
	raw            string
	ExtraFields    map[string]apijson.Field
}

func (r *PublicI9Verification) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicI9VerificationJSON) RawJSON() string {
	return r.raw
}

type PublicI9VerificationStatus string

const (
	PublicI9VerificationStatusNotStarted     PublicI9VerificationStatus = "not_started"
	PublicI9VerificationStatusAwaitingWorker PublicI9VerificationStatus = "awaiting_worker"
	PublicI9VerificationStatusAwaitingAdmin  PublicI9VerificationStatus = "awaiting_admin"
	PublicI9VerificationStatusVerified       PublicI9VerificationStatus = "verified"
)

func (r PublicI9VerificationStatus) IsKnown() bool {
	switch r {
	case PublicI9VerificationStatusNotStarted, PublicI9VerificationStatusAwaitingWorker, PublicI9VerificationStatusAwaitingAdmin, PublicI9VerificationStatusVerified:
		return true
	}
	return false
}

type I9VerificationGetResponse struct {
	// The tag of the i9 verification.
	ID string `json:"id" api:"required"`
	// The id of the worker.
	WorkerID       string                          `json:"workerId" api:"required"`
	Status         I9VerificationGetResponseStatus `json:"status" api:"required"`
	StartDate      string                          `json:"startDate" api:"required"`
	VerifiedAt     time.Time                       `json:"verifiedAt" api:"required,nullable" format:"date-time"`
	RetentionUntil string                          `json:"retentionUntil" api:"required,nullable"`
	DueDate        string                          `json:"dueDate" api:"required,nullable"`
	JSON           i9VerificationGetResponseJSON   `json:"-"`
}

// i9VerificationGetResponseJSON contains the JSON metadata for the struct [I9VerificationGetResponse]
type i9VerificationGetResponseJSON struct {
	ID             apijson.Field
	WorkerID       apijson.Field
	Status         apijson.Field
	StartDate      apijson.Field
	VerifiedAt     apijson.Field
	RetentionUntil apijson.Field
	DueDate        apijson.Field
	raw            string
	ExtraFields    map[string]apijson.Field
}

func (r *I9VerificationGetResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r i9VerificationGetResponseJSON) RawJSON() string {
	return r.raw
}

type I9VerificationGetResponseStatus string

const (
	I9VerificationGetResponseStatusNotStarted     I9VerificationGetResponseStatus = "not_started"
	I9VerificationGetResponseStatusAwaitingWorker I9VerificationGetResponseStatus = "awaiting_worker"
	I9VerificationGetResponseStatusAwaitingAdmin  I9VerificationGetResponseStatus = "awaiting_admin"
	I9VerificationGetResponseStatusVerified       I9VerificationGetResponseStatus = "verified"
)

func (r I9VerificationGetResponseStatus) IsKnown() bool {
	switch r {
	case I9VerificationGetResponseStatusNotStarted, I9VerificationGetResponseStatusAwaitingWorker, I9VerificationGetResponseStatusAwaitingAdmin, I9VerificationGetResponseStatusVerified:
		return true
	}
	return false
}

type I9VerificationListParams struct {
	Limit    param.Field[string] `query:"limit" api:"required"`
	AfterID  param.Field[string] `query:"afterId"`
	BeforeID param.Field[string] `query:"beforeId"`
	// Statuses to include, supplied as repeated parameters. Omit for all workflow
	// states.
	Statuses param.Field[[]I9VerificationListParamsStatus] `query:"statuses"`
	// Worker IDs to include, supplied as repeated parameters. Omit for all workers.
	// Unknown or foreign IDs contribute no matches.
	WorkerIDs param.Field[[]string] `query:"workerIds"`
}

// URLQuery serializes [I9VerificationListParams]'s query parameters as `url.Values`.
func (r I9VerificationListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type I9VerificationListParamsStatus string

const (
	I9VerificationListParamsStatusNotStarted     I9VerificationListParamsStatus = "not_started"
	I9VerificationListParamsStatusAwaitingWorker I9VerificationListParamsStatus = "awaiting_worker"
	I9VerificationListParamsStatusAwaitingAdmin  I9VerificationListParamsStatus = "awaiting_admin"
	I9VerificationListParamsStatusVerified       I9VerificationListParamsStatus = "verified"
)

func (r I9VerificationListParamsStatus) IsKnown() bool {
	switch r {
	case I9VerificationListParamsStatusNotStarted, I9VerificationListParamsStatusAwaitingWorker, I9VerificationListParamsStatusAwaitingAdmin, I9VerificationListParamsStatusVerified:
		return true
	}
	return false
}

type I9VerificationListResponse struct {
	HasMore bool                           `json:"hasMore" api:"required"`
	Count   int64                          `json:"count" api:"required"`
	Data    []PublicI9Verification         `json:"data" api:"required"`
	JSON    i9VerificationListResponseJSON `json:"-"`
}

// i9VerificationListResponseJSON contains the JSON metadata for the struct [I9VerificationListResponse]
type i9VerificationListResponseJSON struct {
	HasMore     apijson.Field
	Count       apijson.Field
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *I9VerificationListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r i9VerificationListResponseJSON) RawJSON() string {
	return r.raw
}
