// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/TeamWarp/warp-go-sdk/internal/apijson"
	"github.com/TeamWarp/warp-go-sdk/internal/apiquery"
	"github.com/TeamWarp/warp-go-sdk/internal/param"
	"github.com/TeamWarp/warp-go-sdk/internal/requestconfig"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// PayrollService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewPayrollService] method instead.
type PayrollService struct {
	Options []option.RequestOption
}

// NewPayrollService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewPayrollService(opts ...option.RequestOption) (r *PayrollService) {
	r = &PayrollService{}
	r.Options = opts
	return
}

// List payroll summaries newest first with stable cursor ordering. Every amount in totals is expressed in fundingCurrency, the currency the employer uses to fund the payroll. Line-derived categories are converted and rounded per paycheck before aggregation, while netPay remains provider-authoritative. Payroll type visibility follows the API key permissions. All lifecycle statuses are included unless statuses are provided.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: PayrollListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PublicPayrollList: A cursor-paginated page of payroll summaries.
//
// Example:
//
//	payroll, err := client.Payroll.List(context.Background(), sdk.PayrollListParams{
//		Limit: sdk.F[string]("limit"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payroll)
func (r *PayrollService) List(ctx context.Context, query PayrollListParams, opts ...option.RequestOption) (res *PublicPayrollList, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/payrolls"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get a payroll by id. Every amount in totals is expressed in fundingCurrency, the currency the employer uses to fund the payroll. Line-derived categories are converted and rounded per paycheck before aggregation, while netPay remains provider-authoritative. Missing, foreign, unauthorized, or unavailable payrolls return 404.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: The payroll ID.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PublicPayrollDetail: A payroll run with funding and lifecycle details. Every amount in totals is expressed in fundingCurrency; line-derived categories are converted and rounded per paycheck before aggregation, while netPay remains provider-authoritative.
//
// Example:
//
//	payroll, err := client.Payroll.Get(context.Background(), "pay_1234")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payroll)
func (r *PayrollService) Get(ctx context.Context, id string, opts ...option.RequestOption) (res *PublicPayrollDetail, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/payrolls/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// List per-worker paycheck summaries newest first with stable cursor ordering. By default, the response includes every worker type visible to the API key, including US W-2 employees, US 1099 contractors, and global contractors; use workerTypes to narrow the results. Payroll type visibility follows the API key permissions. All lifecycle statuses are included unless statuses are provided.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: PayrollListPaychecksParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PublicPaycheckList: A cursor-paginated page of paycheck summaries.
//
// Example:
//
//	payroll, err := client.Payroll.ListPaychecks(context.Background(), sdk.PayrollListPaychecksParams{
//		Limit: sdk.F[string]("limit"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payroll)
func (r *PayrollService) ListPaychecks(ctx context.Context, query PayrollListPaychecksParams, opts ...option.RequestOption) (res *PublicPaycheckList, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/paychecks"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get a paycheck by id. All worker types use the same paycheck schema. Categories that do not apply to a worker are represented by zero-valued totals and empty line-item arrays. For example, a US 1099 contractor with no applicable payroll taxes returns zero `workerTaxes` and `employerTaxes` totals and an empty `taxes` array. Missing, foreign, unauthorized, or unavailable paychecks return 404.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: The paycheck ID.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PublicPaycheckDetail: A paycheck with currency-specific calculation lines, totals grouped by currency, and authoritative parent-payroll funding-currency totals. Source currencies for expenses, benefits, or other inputs are outside this payroll-calculation resource.
//
// Example:
//
//	payroll, err := client.Payroll.GetPaycheck(context.Background(), "pyc_1234")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payroll)
func (r *PayrollService) GetPaycheck(ctx context.Context, id string, opts ...option.RequestOption) (res *PublicPaycheckDetail, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/paychecks/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type PublicPayrollList struct {
	HasMore bool                  `json:"hasMore" api:"required"`
	Count   int64                 `json:"count" api:"required"`
	Data    interface{}           `json:"data" api:"required"`
	JSON    publicPayrollListJSON `json:"-"`
}

// publicPayrollListJSON contains the JSON metadata for the struct [PublicPayrollList]
type publicPayrollListJSON struct {
	HasMore     apijson.Field
	Count       apijson.Field
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollListJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollDetail struct {
	// The tag of the payroll.
	ID              string      `json:"id" api:"required"`
	Type            interface{} `json:"type" api:"required"`
	Subtype         interface{} `json:"subtype" api:"required"`
	Status          interface{} `json:"status" api:"required"`
	FundingCurrency interface{} `json:"fundingCurrency" api:"required"`
	Payday          string      `json:"payday" api:"required"`
	PayPeriod       interface{} `json:"payPeriod" api:"required"`
	// The cadence at which workers are paid.
	PayFrequency     PublicPayFrequency      `json:"payFrequency" api:"required,nullable"`
	Description      string                  `json:"description" api:"required,nullable"`
	ApprovalDeadline string                  `json:"approvalDeadline" api:"required,nullable"`
	PaycheckCount    int64                   `json:"paycheckCount" api:"required"`
	Totals           interface{}             `json:"totals" api:"required"`
	FundingMethod    interface{}             `json:"fundingMethod" api:"required"`
	ReopenDeadline   string                  `json:"reopenDeadline" api:"required,nullable"`
	Timeline         interface{}             `json:"timeline" api:"required"`
	JSON             publicPayrollDetailJSON `json:"-"`
}

// publicPayrollDetailJSON contains the JSON metadata for the struct [PublicPayrollDetail]
type publicPayrollDetailJSON struct {
	ID               apijson.Field
	Type             apijson.Field
	Subtype          apijson.Field
	Status           apijson.Field
	FundingCurrency  apijson.Field
	Payday           apijson.Field
	PayPeriod        apijson.Field
	PayFrequency     apijson.Field
	Description      apijson.Field
	ApprovalDeadline apijson.Field
	PaycheckCount    apijson.Field
	Totals           apijson.Field
	FundingMethod    apijson.Field
	ReopenDeadline   apijson.Field
	Timeline         apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *PublicPayrollDetail) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollDetailJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckList struct {
	HasMore bool                   `json:"hasMore" api:"required"`
	Count   int64                  `json:"count" api:"required"`
	Data    string                 `json:"data" api:"required"`
	JSON    publicPaycheckListJSON `json:"-"`
}

// publicPaycheckListJSON contains the JSON metadata for the struct [PublicPaycheckList]
type publicPaycheckListJSON struct {
	HasMore     apijson.Field
	Count       apijson.Field
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPaycheckList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckListJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckDetail struct {
	// The tag of the paycheck.
	ID             string                   `json:"id" api:"required"`
	Payroll        interface{}              `json:"payroll" api:"required"`
	Worker         interface{}              `json:"worker" api:"required"`
	Status         interface{}              `json:"status" api:"required"`
	Payday         string                   `json:"payday" api:"required"`
	PaymentMethod  interface{}              `json:"paymentMethod" api:"required"`
	Totals         interface{}              `json:"totals" api:"required"`
	Description    string                   `json:"description" api:"required,nullable"`
	ExchangeRates  string                   `json:"exchangeRates" api:"required"`
	ReportedHours  float64                  `json:"reportedHours" api:"required,nullable"`
	Earnings       string                   `json:"earnings" api:"required"`
	Reimbursements string                   `json:"reimbursements" api:"required"`
	Deductions     string                   `json:"deductions" api:"required"`
	Benefits       string                   `json:"benefits" api:"required"`
	Taxes          string                   `json:"taxes" api:"required"`
	JSON           publicPaycheckDetailJSON `json:"-"`
}

// publicPaycheckDetailJSON contains the JSON metadata for the struct [PublicPaycheckDetail]
type publicPaycheckDetailJSON struct {
	ID             apijson.Field
	Payroll        apijson.Field
	Worker         apijson.Field
	Status         apijson.Field
	Payday         apijson.Field
	PaymentMethod  apijson.Field
	Totals         apijson.Field
	Description    apijson.Field
	ExchangeRates  apijson.Field
	ReportedHours  apijson.Field
	Earnings       apijson.Field
	Reimbursements apijson.Field
	Deductions     apijson.Field
	Benefits       apijson.Field
	Taxes          apijson.Field
	raw            string
	ExtraFields    map[string]apijson.Field
}

func (r *PublicPaycheckDetail) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckDetailJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollType string

const (
	PublicPayrollTypeUs     PublicPayrollType = "us"
	PublicPayrollTypeGlobal PublicPayrollType = "global"
)

func (r PublicPayrollType) IsKnown() bool {
	switch r {
	case PublicPayrollTypeUs, PublicPayrollTypeGlobal:
		return true
	}
	return false
}

type PublicPayrollSubtype string

const (
	PublicPayrollSubtypeRegular       PublicPayrollSubtype = "regular"
	PublicPayrollSubtypeOffCycle      PublicPayrollSubtype = "off_cycle"
	PublicPayrollSubtypeBonus         PublicPayrollSubtype = "bonus"
	PublicPayrollSubtypeInvoice       PublicPayrollSubtype = "invoice"
	PublicPayrollSubtypeContractor    PublicPayrollSubtype = "contractor"
	PublicPayrollSubtypeDismissal     PublicPayrollSubtype = "dismissal"
	PublicPayrollSubtypeReimbursement PublicPayrollSubtype = "reimbursement"
	PublicPayrollSubtypeManual        PublicPayrollSubtype = "manual"
)

func (r PublicPayrollSubtype) IsKnown() bool {
	switch r {
	case PublicPayrollSubtypeRegular, PublicPayrollSubtypeOffCycle, PublicPayrollSubtypeBonus, PublicPayrollSubtypeInvoice, PublicPayrollSubtypeContractor, PublicPayrollSubtypeDismissal, PublicPayrollSubtypeReimbursement, PublicPayrollSubtypeManual:
		return true
	}
	return false
}

type PublicPayrollStatus string

const (
	PublicPayrollStatusDraft         PublicPayrollStatus = "draft"
	PublicPayrollStatusPending       PublicPayrollStatus = "pending"
	PublicPayrollStatusProcessing    PublicPayrollStatus = "processing"
	PublicPayrollStatusPartiallyPaid PublicPayrollStatus = "partially_paid"
	PublicPayrollStatusProcessed     PublicPayrollStatus = "processed"
	PublicPayrollStatusFailed        PublicPayrollStatus = "failed"
	PublicPayrollStatusVoided        PublicPayrollStatus = "voided"
)

func (r PublicPayrollStatus) IsKnown() bool {
	switch r {
	case PublicPayrollStatusDraft, PublicPayrollStatusPending, PublicPayrollStatusProcessing, PublicPayrollStatusPartiallyPaid, PublicPayrollStatusProcessed, PublicPayrollStatusFailed, PublicPayrollStatusVoided:
		return true
	}
	return false
}

type PublicPayrollCurrency string

const (
	PublicPayrollCurrencyUsd PublicPayrollCurrency = "USD"
	PublicPayrollCurrencyAud PublicPayrollCurrency = "AUD"
	PublicPayrollCurrencyBgn PublicPayrollCurrency = "BGN"
	PublicPayrollCurrencyBrl PublicPayrollCurrency = "BRL"
	PublicPayrollCurrencyCad PublicPayrollCurrency = "CAD"
	PublicPayrollCurrencyChf PublicPayrollCurrency = "CHF"
	PublicPayrollCurrencyCzk PublicPayrollCurrency = "CZK"
	PublicPayrollCurrencyDkk PublicPayrollCurrency = "DKK"
	PublicPayrollCurrencyEur PublicPayrollCurrency = "EUR"
	PublicPayrollCurrencyGbp PublicPayrollCurrency = "GBP"
	PublicPayrollCurrencyHkd PublicPayrollCurrency = "HKD"
	PublicPayrollCurrencyHuf PublicPayrollCurrency = "HUF"
	PublicPayrollCurrencyIdr PublicPayrollCurrency = "IDR"
	PublicPayrollCurrencyInr PublicPayrollCurrency = "INR"
	PublicPayrollCurrencyJpy PublicPayrollCurrency = "JPY"
	PublicPayrollCurrencyMyr PublicPayrollCurrency = "MYR"
	PublicPayrollCurrencyNok PublicPayrollCurrency = "NOK"
	PublicPayrollCurrencyNzd PublicPayrollCurrency = "NZD"
	PublicPayrollCurrencyCny PublicPayrollCurrency = "CNY"
	PublicPayrollCurrencyPln PublicPayrollCurrency = "PLN"
	PublicPayrollCurrencyRon PublicPayrollCurrency = "RON"
	PublicPayrollCurrencyTry PublicPayrollCurrency = "TRY"
	PublicPayrollCurrencySek PublicPayrollCurrency = "SEK"
	PublicPayrollCurrencySgd PublicPayrollCurrency = "SGD"
	PublicPayrollCurrencyAed PublicPayrollCurrency = "AED"
	PublicPayrollCurrencyArs PublicPayrollCurrency = "ARS"
	PublicPayrollCurrencyBdt PublicPayrollCurrency = "BDT"
	PublicPayrollCurrencyBwp PublicPayrollCurrency = "BWP"
	PublicPayrollCurrencyClp PublicPayrollCurrency = "CLP"
	PublicPayrollCurrencyCop PublicPayrollCurrency = "COP"
	PublicPayrollCurrencyCrc PublicPayrollCurrency = "CRC"
	PublicPayrollCurrencyEgp PublicPayrollCurrency = "EGP"
	PublicPayrollCurrencyFjd PublicPayrollCurrency = "FJD"
	PublicPayrollCurrencyGel PublicPayrollCurrency = "GEL"
	PublicPayrollCurrencyGhs PublicPayrollCurrency = "GHS"
	PublicPayrollCurrencyIls PublicPayrollCurrency = "ILS"
	PublicPayrollCurrencyKes PublicPayrollCurrency = "KES"
	PublicPayrollCurrencyKrw PublicPayrollCurrency = "KRW"
	PublicPayrollCurrencyLkr PublicPayrollCurrency = "LKR"
	PublicPayrollCurrencyMad PublicPayrollCurrency = "MAD"
	PublicPayrollCurrencyMxn PublicPayrollCurrency = "MXN"
	PublicPayrollCurrencyNpr PublicPayrollCurrency = "NPR"
	PublicPayrollCurrencyPhp PublicPayrollCurrency = "PHP"
	PublicPayrollCurrencyPkr PublicPayrollCurrency = "PKR"
	PublicPayrollCurrencyThb PublicPayrollCurrency = "THB"
	PublicPayrollCurrencyUah PublicPayrollCurrency = "UAH"
	PublicPayrollCurrencyUgx PublicPayrollCurrency = "UGX"
	PublicPayrollCurrencyUyu PublicPayrollCurrency = "UYU"
	PublicPayrollCurrencyVnd PublicPayrollCurrency = "VND"
	PublicPayrollCurrencyZar PublicPayrollCurrency = "ZAR"
	PublicPayrollCurrencyZmw PublicPayrollCurrency = "ZMW"
	PublicPayrollCurrencyTnd PublicPayrollCurrency = "TND"
	PublicPayrollCurrencyNgn PublicPayrollCurrency = "NGN"
	PublicPayrollCurrencyRsd PublicPayrollCurrency = "RSD"
	PublicPayrollCurrencyTwd PublicPayrollCurrency = "TWD"
	PublicPayrollCurrencyGtq PublicPayrollCurrency = "GTQ"
	PublicPayrollCurrencyHnl PublicPayrollCurrency = "HNL"
	PublicPayrollCurrencyDop PublicPayrollCurrency = "DOP"
	PublicPayrollCurrencySar PublicPayrollCurrency = "SAR"
	PublicPayrollCurrencyXaf PublicPayrollCurrency = "XAF"
	PublicPayrollCurrencyPen PublicPayrollCurrency = "PEN"
	PublicPayrollCurrencyBob PublicPayrollCurrency = "BOB"
)

func (r PublicPayrollCurrency) IsKnown() bool {
	switch r {
	case PublicPayrollCurrencyUsd, PublicPayrollCurrencyAud, PublicPayrollCurrencyBgn, PublicPayrollCurrencyBrl, PublicPayrollCurrencyCad, PublicPayrollCurrencyChf, PublicPayrollCurrencyCzk, PublicPayrollCurrencyDkk, PublicPayrollCurrencyEur, PublicPayrollCurrencyGbp, PublicPayrollCurrencyHkd, PublicPayrollCurrencyHuf, PublicPayrollCurrencyIdr, PublicPayrollCurrencyInr, PublicPayrollCurrencyJpy, PublicPayrollCurrencyMyr, PublicPayrollCurrencyNok, PublicPayrollCurrencyNzd, PublicPayrollCurrencyCny, PublicPayrollCurrencyPln, PublicPayrollCurrencyRon, PublicPayrollCurrencyTry, PublicPayrollCurrencySek, PublicPayrollCurrencySgd, PublicPayrollCurrencyAed, PublicPayrollCurrencyArs, PublicPayrollCurrencyBdt, PublicPayrollCurrencyBwp, PublicPayrollCurrencyClp, PublicPayrollCurrencyCop, PublicPayrollCurrencyCrc, PublicPayrollCurrencyEgp, PublicPayrollCurrencyFjd, PublicPayrollCurrencyGel, PublicPayrollCurrencyGhs, PublicPayrollCurrencyIls, PublicPayrollCurrencyKes, PublicPayrollCurrencyKrw, PublicPayrollCurrencyLkr, PublicPayrollCurrencyMad, PublicPayrollCurrencyMxn, PublicPayrollCurrencyNpr, PublicPayrollCurrencyPhp, PublicPayrollCurrencyPkr, PublicPayrollCurrencyThb, PublicPayrollCurrencyUah, PublicPayrollCurrencyUgx, PublicPayrollCurrencyUyu, PublicPayrollCurrencyVnd, PublicPayrollCurrencyZar, PublicPayrollCurrencyZmw, PublicPayrollCurrencyTnd, PublicPayrollCurrencyNgn, PublicPayrollCurrencyRsd, PublicPayrollCurrencyTwd, PublicPayrollCurrencyGtq, PublicPayrollCurrencyHnl, PublicPayrollCurrencyDop, PublicPayrollCurrencySar, PublicPayrollCurrencyXaf, PublicPayrollCurrencyPen, PublicPayrollCurrencyBob:
		return true
	}
	return false
}

type PublicPayPeriod struct {
	StartDate string              `json:"startDate" api:"required"`
	EndDate   string              `json:"endDate" api:"required"`
	JSON      publicPayPeriodJSON `json:"-"`
}

// publicPayPeriodJSON contains the JSON metadata for the struct [PublicPayPeriod]
type publicPayPeriodJSON struct {
	StartDate   apijson.Field
	EndDate     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayPeriod) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayPeriodJSON) RawJSON() string {
	return r.raw
}

type PublicPayFrequency string

const (
	PublicPayFrequencyWeekly      PublicPayFrequency = "weekly"
	PublicPayFrequencyBiweekly    PublicPayFrequency = "biweekly"
	PublicPayFrequencyMonthly     PublicPayFrequency = "monthly"
	PublicPayFrequencySemimonthly PublicPayFrequency = "semimonthly"
	PublicPayFrequencyQuarterly   PublicPayFrequency = "quarterly"
	PublicPayFrequencyAnnually    PublicPayFrequency = "annually"
)

func (r PublicPayFrequency) IsKnown() bool {
	switch r {
	case PublicPayFrequencyWeekly, PublicPayFrequencyBiweekly, PublicPayFrequencyMonthly, PublicPayFrequencySemimonthly, PublicPayFrequencyQuarterly, PublicPayFrequencyAnnually:
		return true
	}
	return false
}

type PublicPayrollDetailTotals struct {
	// The provider-reported amount the employer must fund for the payroll, when
	// available.
	CashRequirement PublicCurrencyMoneyAmount11 `json:"cashRequirement" api:"required,nullable"`
	// Gross earnings before worker taxes, deductions, and benefit contributions.
	// Reimbursements are reported separately.
	GrossPay PublicCurrencyMoneyAmount `json:"grossPay" api:"required"`
	// The provider-calculated amount to send for workers: gross pay plus
	// reimbursements, less worker taxes, deductions, and benefit contributions. It
	// excludes payment execution fees and may differ from recomputed totals because of
	// provider and FX rounding.
	NetPay PublicCurrencyMoneyAmount1 `json:"netPay" api:"required"`
	// Amounts reimbursed to workers in addition to gross pay. Reimbursements increase
	// net pay and employer cost.
	Reimbursements PublicCurrencyMoneyAmount2 `json:"reimbursements" api:"required"`
	// Payroll taxes withheld from worker pay, reducing net pay.
	WorkerTaxes PublicCurrencyMoneyAmount3 `json:"workerTaxes" api:"required"`
	// Payroll taxes paid by the employer in addition to gross pay.
	EmployerTaxes PublicCurrencyMoneyAmount4 `json:"employerTaxes" api:"required"`
	// Non-benefit amounts deducted from worker pay before taxes, reducing taxable pay
	// and net pay.
	PreTaxDeductions PublicCurrencyMoneyAmount5 `json:"preTaxDeductions" api:"required"`
	// Non-benefit amounts deducted from worker pay after taxes, reducing net pay.
	PostTaxDeductions PublicCurrencyMoneyAmount6 `json:"postTaxDeductions" api:"required"`
	// Amounts workers pay toward benefits, deducted from their pay.
	WorkerBenefitContributions PublicCurrencyMoneyAmount7 `json:"workerBenefitContributions" api:"required"`
	// Amounts the employer pays toward worker benefits in addition to gross pay.
	EmployerBenefitContributions PublicCurrencyMoneyAmount8 `json:"employerBenefitContributions" api:"required"`
	// Banking and transaction fees paid by the employer to fund and pay the payroll.
	TransactionFees PublicCurrencyMoneyAmount9 `json:"transactionFees" api:"required"`
	// The employer's total payroll cost: gross pay, reimbursements, employer taxes,
	// employer benefit contributions, and transaction fees.
	TotalCost PublicCurrencyMoneyAmount10   `json:"totalCost" api:"required"`
	JSON      publicPayrollDetailTotalsJSON `json:"-"`
}

// publicPayrollDetailTotalsJSON contains the JSON metadata for the struct [PublicPayrollDetailTotals]
type publicPayrollDetailTotalsJSON struct {
	CashRequirement              apijson.Field
	GrossPay                     apijson.Field
	NetPay                       apijson.Field
	Reimbursements               apijson.Field
	WorkerTaxes                  apijson.Field
	EmployerTaxes                apijson.Field
	PreTaxDeductions             apijson.Field
	PostTaxDeductions            apijson.Field
	WorkerBenefitContributions   apijson.Field
	EmployerBenefitContributions apijson.Field
	TransactionFees              apijson.Field
	TotalCost                    apijson.Field
	raw                          string
	ExtraFields                  map[string]apijson.Field
}

func (r *PublicPayrollDetailTotals) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollDetailTotalsJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollFundingMethod string

const (
	PublicPayrollFundingMethodACH  PublicPayrollFundingMethod = "ach"
	PublicPayrollFundingMethodWire PublicPayrollFundingMethod = "wire"
)

func (r PublicPayrollFundingMethod) IsKnown() bool {
	switch r {
	case PublicPayrollFundingMethodACH, PublicPayrollFundingMethodWire:
		return true
	}
	return false
}

type PublicPayrollTimeline struct {
	ApprovedAt string                    `json:"approvedAt" api:"required,nullable"`
	JSON       publicPayrollTimelineJSON `json:"-"`
}

// publicPayrollTimelineJSON contains the JSON metadata for the struct [PublicPayrollTimeline]
type publicPayrollTimelineJSON struct {
	ApprovedAt  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollTimeline) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollTimelineJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckPayroll struct {
	// The tag of the payroll.
	ID              string      `json:"id" api:"required"`
	Type            interface{} `json:"type" api:"required"`
	Subtype         interface{} `json:"subtype" api:"required"`
	Status          interface{} `json:"status" api:"required"`
	FundingCurrency interface{} `json:"fundingCurrency" api:"required"`
	PayPeriod       interface{} `json:"payPeriod" api:"required"`
	// The cadence at which workers are paid.
	PayFrequency PublicPayFrequency        `json:"payFrequency" api:"required,nullable"`
	JSON         publicPaycheckPayrollJSON `json:"-"`
}

// publicPaycheckPayrollJSON contains the JSON metadata for the struct [PublicPaycheckPayroll]
type publicPaycheckPayrollJSON struct {
	ID              apijson.Field
	Type            apijson.Field
	Subtype         apijson.Field
	Status          apijson.Field
	FundingCurrency apijson.Field
	PayPeriod       apijson.Field
	PayFrequency    apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *PublicPaycheckPayroll) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckPayrollJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckWorker struct {
	// The worker id.
	ID string `json:"id" api:"required"`
	// The worker first name.
	FirstName string `json:"firstName" api:"required"`
	// The worker last name.
	LastName    string                         `json:"lastName" api:"required"`
	DisplayName string                         `json:"displayName" api:"required"`
	WorkerType  PublicPaycheckWorkerWorkerType `json:"workerType" api:"required"`
	JSON        publicPaycheckWorkerJSON       `json:"-"`
}

// publicPaycheckWorkerJSON contains the JSON metadata for the struct [PublicPaycheckWorker]
type publicPaycheckWorkerJSON struct {
	ID          apijson.Field
	FirstName   apijson.Field
	LastName    apijson.Field
	DisplayName apijson.Field
	WorkerType  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPaycheckWorker) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckWorkerJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckWorkerWorkerType string

const (
	PublicPaycheckWorkerWorkerTypeUsW2             PublicPaycheckWorkerWorkerType = "us_w2"
	PublicPaycheckWorkerWorkerTypeUs1099           PublicPaycheckWorkerWorkerType = "us_1099"
	PublicPaycheckWorkerWorkerTypeGlobalContractor PublicPaycheckWorkerWorkerType = "global_contractor"
	PublicPaycheckWorkerWorkerTypeGlobalEmployee   PublicPaycheckWorkerWorkerType = "global_employee"
)

func (r PublicPaycheckWorkerWorkerType) IsKnown() bool {
	switch r {
	case PublicPaycheckWorkerWorkerTypeUsW2, PublicPaycheckWorkerWorkerTypeUs1099, PublicPaycheckWorkerWorkerTypeGlobalContractor, PublicPaycheckWorkerWorkerTypeGlobalEmployee:
		return true
	}
	return false
}

type PublicPaycheckStatus string

const (
	PublicPaycheckStatusDraft         PublicPaycheckStatus = "draft"
	PublicPaycheckStatusPending       PublicPaycheckStatus = "pending"
	PublicPaycheckStatusProcessing    PublicPaycheckStatus = "processing"
	PublicPaycheckStatusDebited       PublicPaycheckStatus = "debited"
	PublicPaycheckStatusCredited      PublicPaycheckStatus = "credited"
	PublicPaycheckStatusPartiallyPaid PublicPaycheckStatus = "partially_paid"
	PublicPaycheckStatusProcessed     PublicPaycheckStatus = "processed"
	PublicPaycheckStatusFailed        PublicPaycheckStatus = "failed"
	PublicPaycheckStatusVoided        PublicPaycheckStatus = "voided"
)

func (r PublicPaycheckStatus) IsKnown() bool {
	switch r {
	case PublicPaycheckStatusDraft, PublicPaycheckStatusPending, PublicPaycheckStatusProcessing, PublicPaycheckStatusDebited, PublicPaycheckStatusCredited, PublicPaycheckStatusPartiallyPaid, PublicPaycheckStatusProcessed, PublicPaycheckStatusFailed, PublicPaycheckStatusVoided:
		return true
	}
	return false
}

type PublicPaycheckPaymentMethod string

const (
	PublicPaycheckPaymentMethodDirectDeposit PublicPaycheckPaymentMethod = "direct_deposit"
	PublicPaycheckPaymentMethodManual        PublicPaycheckPaymentMethod = "manual"
)

func (r PublicPaycheckPaymentMethod) IsKnown() bool {
	switch r {
	case PublicPaycheckPaymentMethodDirectDeposit, PublicPaycheckPaymentMethodManual:
		return true
	}
	return false
}

type PublicPaycheckDetailTotals struct {
	ByCurrency        string                         `json:"byCurrency" api:"required"`
	InFundingCurrency interface{}                    `json:"inFundingCurrency" api:"required"`
	JSON              publicPaycheckDetailTotalsJSON `json:"-"`
}

// publicPaycheckDetailTotalsJSON contains the JSON metadata for the struct [PublicPaycheckDetailTotals]
type publicPaycheckDetailTotalsJSON struct {
	ByCurrency        apijson.Field
	InFundingCurrency apijson.Field
	raw               string
	ExtraFields       map[string]apijson.Field
}

func (r *PublicPaycheckDetailTotals) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckDetailTotalsJSON) RawJSON() string {
	return r.raw
}

type PublicFundingPayrollTotals struct {
	// Gross earnings before worker taxes, deductions, and benefit contributions.
	// Reimbursements are reported separately.
	GrossPay PublicCurrencyMoneyAmount `json:"grossPay" api:"required"`
	// The provider-calculated amount to send for workers: gross pay plus
	// reimbursements, less worker taxes, deductions, and benefit contributions. It
	// excludes payment execution fees and may differ from recomputed totals because of
	// provider and FX rounding.
	NetPay PublicCurrencyMoneyAmount1 `json:"netPay" api:"required"`
	// Amounts reimbursed to workers in addition to gross pay. Reimbursements increase
	// net pay and employer cost.
	Reimbursements PublicCurrencyMoneyAmount2 `json:"reimbursements" api:"required"`
	// Payroll taxes withheld from worker pay, reducing net pay.
	WorkerTaxes PublicCurrencyMoneyAmount3 `json:"workerTaxes" api:"required"`
	// Payroll taxes paid by the employer in addition to gross pay.
	EmployerTaxes PublicCurrencyMoneyAmount4 `json:"employerTaxes" api:"required"`
	// Non-benefit amounts deducted from worker pay before taxes, reducing taxable pay
	// and net pay.
	PreTaxDeductions PublicCurrencyMoneyAmount5 `json:"preTaxDeductions" api:"required"`
	// Non-benefit amounts deducted from worker pay after taxes, reducing net pay.
	PostTaxDeductions PublicCurrencyMoneyAmount6 `json:"postTaxDeductions" api:"required"`
	// Amounts workers pay toward benefits, deducted from their pay.
	WorkerBenefitContributions PublicCurrencyMoneyAmount7 `json:"workerBenefitContributions" api:"required"`
	// Amounts the employer pays toward worker benefits in addition to gross pay.
	EmployerBenefitContributions PublicCurrencyMoneyAmount8 `json:"employerBenefitContributions" api:"required"`
	// Banking and transaction fees paid by the employer to fund and pay the payroll.
	TransactionFees PublicCurrencyMoneyAmount9 `json:"transactionFees" api:"required"`
	// The employer's total payroll cost: gross pay, reimbursements, employer taxes,
	// employer benefit contributions, and transaction fees.
	TotalCost PublicCurrencyMoneyAmount10    `json:"totalCost" api:"required"`
	JSON      publicFundingPayrollTotalsJSON `json:"-"`
}

// publicFundingPayrollTotalsJSON contains the JSON metadata for the struct [PublicFundingPayrollTotals]
type publicFundingPayrollTotalsJSON struct {
	GrossPay                     apijson.Field
	NetPay                       apijson.Field
	Reimbursements               apijson.Field
	WorkerTaxes                  apijson.Field
	EmployerTaxes                apijson.Field
	PreTaxDeductions             apijson.Field
	PostTaxDeductions            apijson.Field
	WorkerBenefitContributions   apijson.Field
	EmployerBenefitContributions apijson.Field
	TransactionFees              apijson.Field
	TotalCost                    apijson.Field
	raw                          string
	ExtraFields                  map[string]apijson.Field
}

func (r *PublicFundingPayrollTotals) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicFundingPayrollTotalsJSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount11 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                          `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount11JSON `json:"-"`
}

// publicCurrencyMoneyAmount11JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount11]
type publicCurrencyMoneyAmount11JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount11) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount11JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                        `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmountJSON `json:"-"`
}

// publicCurrencyMoneyAmountJSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount]
type publicCurrencyMoneyAmountJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmountJSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount1 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                         `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount1JSON `json:"-"`
}

// publicCurrencyMoneyAmount1JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount1]
type publicCurrencyMoneyAmount1JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount1) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount1JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount2 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                         `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount2JSON `json:"-"`
}

// publicCurrencyMoneyAmount2JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount2]
type publicCurrencyMoneyAmount2JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount2) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount2JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount3 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                         `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount3JSON `json:"-"`
}

// publicCurrencyMoneyAmount3JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount3]
type publicCurrencyMoneyAmount3JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount3) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount3JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount4 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                         `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount4JSON `json:"-"`
}

// publicCurrencyMoneyAmount4JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount4]
type publicCurrencyMoneyAmount4JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount4) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount4JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount5 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                         `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount5JSON `json:"-"`
}

// publicCurrencyMoneyAmount5JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount5]
type publicCurrencyMoneyAmount5JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount5) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount5JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount6 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                         `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount6JSON `json:"-"`
}

// publicCurrencyMoneyAmount6JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount6]
type publicCurrencyMoneyAmount6JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount6) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount6JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount7 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                         `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount7JSON `json:"-"`
}

// publicCurrencyMoneyAmount7JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount7]
type publicCurrencyMoneyAmount7JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount7) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount7JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount8 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                         `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount8JSON `json:"-"`
}

// publicCurrencyMoneyAmount8JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount8]
type publicCurrencyMoneyAmount8JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount8) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount8JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount9 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                         `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount9JSON `json:"-"`
}

// publicCurrencyMoneyAmount9JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount9]
type publicCurrencyMoneyAmount9JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount9) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount9JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount10 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                          `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount10JSON `json:"-"`
}

// publicCurrencyMoneyAmount10JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount10]
type publicCurrencyMoneyAmount10JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount10) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount10JSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckSummaryTotals struct {
	ByCurrency        string                          `json:"byCurrency" api:"required"`
	InFundingCurrency interface{}                     `json:"inFundingCurrency" api:"required"`
	JSON              publicPaycheckSummaryTotalsJSON `json:"-"`
}

// publicPaycheckSummaryTotalsJSON contains the JSON metadata for the struct [PublicPaycheckSummaryTotals]
type publicPaycheckSummaryTotalsJSON struct {
	ByCurrency        apijson.Field
	InFundingCurrency apijson.Field
	raw               string
	ExtraFields       map[string]apijson.Field
}

func (r *PublicPaycheckSummaryTotals) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckSummaryTotalsJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckCurrencyTotals struct {
	Currency interface{} `json:"currency" api:"required"`
	// Gross earnings before worker taxes, deductions, and benefit contributions.
	// Reimbursements are reported separately.
	GrossPay PublicCurrencyMoneyAmount13 `json:"grossPay" api:"required"`
	// Calculated net pay after reimbursements, worker taxes, deductions, and benefit
	// contributions. It excludes payment execution fees and may differ from the amount
	// the worker ultimately receives.
	NetPay PublicCurrencyMoneyAmount12 `json:"netPay" api:"required"`
	// Amounts reimbursed to the worker in addition to gross pay. Reimbursements
	// increase net pay and employer cost.
	Reimbursements PublicCurrencyMoneyAmount14 `json:"reimbursements" api:"required"`
	// Payroll taxes withheld from the worker's pay, reducing net pay.
	WorkerTaxes PublicCurrencyMoneyAmount15 `json:"workerTaxes" api:"required"`
	// Payroll taxes paid by the employer in addition to gross pay.
	EmployerTaxes PublicCurrencyMoneyAmount16 `json:"employerTaxes" api:"required"`
	// Non-benefit amounts deducted from the worker's pay before taxes, reducing
	// taxable pay and net pay.
	PreTaxDeductions PublicCurrencyMoneyAmount17 `json:"preTaxDeductions" api:"required"`
	// Non-benefit amounts deducted from the worker's pay after taxes, reducing net
	// pay.
	PostTaxDeductions PublicCurrencyMoneyAmount18 `json:"postTaxDeductions" api:"required"`
	// Amounts the worker pays toward benefits, deducted from their pay.
	WorkerBenefitContributions PublicCurrencyMoneyAmount19 `json:"workerBenefitContributions" api:"required"`
	// Amounts the employer pays toward the worker's benefits in addition to gross pay.
	EmployerBenefitContributions PublicCurrencyMoneyAmount20      `json:"employerBenefitContributions" api:"required"`
	JSON                         publicPaycheckCurrencyTotalsJSON `json:"-"`
}

// publicPaycheckCurrencyTotalsJSON contains the JSON metadata for the struct [PublicPaycheckCurrencyTotals]
type publicPaycheckCurrencyTotalsJSON struct {
	Currency                     apijson.Field
	GrossPay                     apijson.Field
	NetPay                       apijson.Field
	Reimbursements               apijson.Field
	WorkerTaxes                  apijson.Field
	EmployerTaxes                apijson.Field
	PreTaxDeductions             apijson.Field
	PostTaxDeductions            apijson.Field
	WorkerBenefitContributions   apijson.Field
	EmployerBenefitContributions apijson.Field
	raw                          string
	ExtraFields                  map[string]apijson.Field
}

func (r *PublicPaycheckCurrencyTotals) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckCurrencyTotalsJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollMoneyAmount struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount   int64       `json:"amount" api:"required"`
	Currency interface{} `json:"currency" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                       `json:"display" api:"required"`
	JSON    publicPayrollMoneyAmountJSON `json:"-"`
}

// publicPayrollMoneyAmountJSON contains the JSON metadata for the struct [PublicPayrollMoneyAmount]
type publicPayrollMoneyAmountJSON struct {
	Amount      apijson.Field
	Currency    apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollMoneyAmount) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollMoneyAmountJSON) RawJSON() string {
	return r.raw
}

type PublicHourlyRate struct {
	Amount   interface{}          `json:"amount" api:"required"`
	Currency interface{}          `json:"currency" api:"required"`
	Per      PublicHourlyRatePer  `json:"per" api:"required"`
	JSON     publicHourlyRateJSON `json:"-"`
}

// publicHourlyRateJSON contains the JSON metadata for the struct [PublicHourlyRate]
type publicHourlyRateJSON struct {
	Amount      apijson.Field
	Currency    apijson.Field
	Per         apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicHourlyRate) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicHourlyRateJSON) RawJSON() string {
	return r.raw
}

type PublicHourlyRatePer string

const (
	PublicHourlyRatePerHour PublicHourlyRatePer = "hour"
)

func (r PublicHourlyRatePer) IsKnown() bool {
	switch r {
	case PublicHourlyRatePerHour:
		return true
	}
	return false
}

type PublicPayrollMoneyAmount1 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount   int64       `json:"amount" api:"required"`
	Currency interface{} `json:"currency" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                        `json:"display" api:"required"`
	JSON    publicPayrollMoneyAmount1JSON `json:"-"`
}

// publicPayrollMoneyAmount1JSON contains the JSON metadata for the struct [PublicPayrollMoneyAmount1]
type publicPayrollMoneyAmount1JSON struct {
	Amount      apijson.Field
	Currency    apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollMoneyAmount1) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollMoneyAmount1JSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckDeductionTaxTreatment string

const (
	PublicPaycheckDeductionTaxTreatmentPreTax  PublicPaycheckDeductionTaxTreatment = "pre_tax"
	PublicPaycheckDeductionTaxTreatmentPostTax PublicPaycheckDeductionTaxTreatment = "post_tax"
)

func (r PublicPaycheckDeductionTaxTreatment) IsKnown() bool {
	switch r {
	case PublicPaycheckDeductionTaxTreatmentPreTax, PublicPaycheckDeductionTaxTreatmentPostTax:
		return true
	}
	return false
}

type PublicPayrollMoneyAmount2 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount   int64       `json:"amount" api:"required"`
	Currency interface{} `json:"currency" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                        `json:"display" api:"required"`
	JSON    publicPayrollMoneyAmount2JSON `json:"-"`
}

// publicPayrollMoneyAmount2JSON contains the JSON metadata for the struct [PublicPayrollMoneyAmount2]
type publicPayrollMoneyAmount2JSON struct {
	Amount      apijson.Field
	Currency    apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollMoneyAmount2) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollMoneyAmount2JSON) RawJSON() string {
	return r.raw
}

type PublicPayrollMoneyAmount3 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount   int64       `json:"amount" api:"required"`
	Currency interface{} `json:"currency" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                        `json:"display" api:"required"`
	JSON    publicPayrollMoneyAmount3JSON `json:"-"`
}

// publicPayrollMoneyAmount3JSON contains the JSON metadata for the struct [PublicPayrollMoneyAmount3]
type publicPayrollMoneyAmount3JSON struct {
	Amount      apijson.Field
	Currency    apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollMoneyAmount3) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollMoneyAmount3JSON) RawJSON() string {
	return r.raw
}

type PublicPayrollMoneyAmount4 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount   int64       `json:"amount" api:"required"`
	Currency interface{} `json:"currency" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                        `json:"display" api:"required"`
	JSON    publicPayrollMoneyAmount4JSON `json:"-"`
}

// publicPayrollMoneyAmount4JSON contains the JSON metadata for the struct [PublicPayrollMoneyAmount4]
type publicPayrollMoneyAmount4JSON struct {
	Amount      apijson.Field
	Currency    apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollMoneyAmount4) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollMoneyAmount4JSON) RawJSON() string {
	return r.raw
}

type PublicTaxPayer string

const (
	PublicTaxPayerWorker   PublicTaxPayer = "worker"
	PublicTaxPayerEmployer PublicTaxPayer = "employer"
)

func (r PublicTaxPayer) IsKnown() bool {
	switch r {
	case PublicTaxPayerWorker, PublicTaxPayerEmployer:
		return true
	}
	return false
}

type PublicPayrollMoneyAmount5 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount   int64       `json:"amount" api:"required"`
	Currency interface{} `json:"currency" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                        `json:"display" api:"required"`
	JSON    publicPayrollMoneyAmount5JSON `json:"-"`
}

// publicPayrollMoneyAmount5JSON contains the JSON metadata for the struct [PublicPayrollMoneyAmount5]
type publicPayrollMoneyAmount5JSON struct {
	Amount      apijson.Field
	Currency    apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollMoneyAmount5) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollMoneyAmount5JSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckSummaryCurrencyTotals struct {
	Currency interface{} `json:"currency" api:"required"`
	// Calculated net pay after reimbursements, worker taxes, deductions, and benefit
	// contributions. It excludes payment execution fees and may differ from the amount
	// the worker ultimately receives.
	NetPay PublicCurrencyMoneyAmount12             `json:"netPay" api:"required"`
	JSON   publicPaycheckSummaryCurrencyTotalsJSON `json:"-"`
}

// publicPaycheckSummaryCurrencyTotalsJSON contains the JSON metadata for the struct [PublicPaycheckSummaryCurrencyTotals]
type publicPaycheckSummaryCurrencyTotalsJSON struct {
	Currency    apijson.Field
	NetPay      apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPaycheckSummaryCurrencyTotals) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckSummaryCurrencyTotalsJSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount13 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                          `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount13JSON `json:"-"`
}

// publicCurrencyMoneyAmount13JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount13]
type publicCurrencyMoneyAmount13JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount13) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount13JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount12 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                          `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount12JSON `json:"-"`
}

// publicCurrencyMoneyAmount12JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount12]
type publicCurrencyMoneyAmount12JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount12) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount12JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount14 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                          `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount14JSON `json:"-"`
}

// publicCurrencyMoneyAmount14JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount14]
type publicCurrencyMoneyAmount14JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount14) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount14JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount15 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                          `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount15JSON `json:"-"`
}

// publicCurrencyMoneyAmount15JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount15]
type publicCurrencyMoneyAmount15JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount15) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount15JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount16 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                          `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount16JSON `json:"-"`
}

// publicCurrencyMoneyAmount16JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount16]
type publicCurrencyMoneyAmount16JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount16) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount16JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount17 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                          `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount17JSON `json:"-"`
}

// publicCurrencyMoneyAmount17JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount17]
type publicCurrencyMoneyAmount17JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount17) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount17JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount18 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                          `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount18JSON `json:"-"`
}

// publicCurrencyMoneyAmount18JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount18]
type publicCurrencyMoneyAmount18JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount18) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount18JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount19 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                          `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount19JSON `json:"-"`
}

// publicCurrencyMoneyAmount19JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount19]
type publicCurrencyMoneyAmount19JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount19) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount19JSON) RawJSON() string {
	return r.raw
}

type PublicCurrencyMoneyAmount20 struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                          `json:"display" api:"required"`
	JSON    publicCurrencyMoneyAmount20JSON `json:"-"`
}

// publicCurrencyMoneyAmount20JSON contains the JSON metadata for the struct [PublicCurrencyMoneyAmount20]
type publicCurrencyMoneyAmount20JSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicCurrencyMoneyAmount20) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicCurrencyMoneyAmount20JSON) RawJSON() string {
	return r.raw
}

type PayrollListParams struct {
	// The maximum number of payrolls to return, from 1 to 50.
	Limit param.Field[string] `query:"limit" api:"required"`
	// Return payrolls after this payroll ID in the stable cursor order. Cannot be used
	// with beforeId.
	AfterID param.Field[string] `query:"afterId"`
	// Return payrolls before this payroll ID in the stable cursor order. Cannot be
	// used with afterId.
	BeforeID param.Field[string] `query:"beforeId"`
	// Pay cadences to include.
	PayFrequencies param.Field[[]PublicPayFrequency] `query:"payFrequencies"`
	// Exclusive end of the half-open pay-period-end range.
	PayPeriodEndBefore param.Field[string] `query:"payPeriodEndBefore"`
	// Inclusive start of the half-open pay-period-end range.
	PayPeriodEndOnOrAfter param.Field[string] `query:"payPeriodEndOnOrAfter"`
	// Exclusive end of the half-open payday range.
	PaydayBefore param.Field[string] `query:"paydayBefore"`
	// Inclusive start of the half-open payday range.
	PaydayOnOrAfter param.Field[string] `query:"paydayOnOrAfter"`
	// Lifecycle statuses to include. Omit to include every status.
	Statuses param.Field[[]PublicPayrollStatus] `query:"statuses"`
	// Payroll subtypes to include.
	Subtypes param.Field[[]PublicPayrollSubtype] `query:"subtypes"`
	// Payroll calculation types to include.
	Types param.Field[[]PublicPayrollType] `query:"types"`
}

// URLQuery serializes [PayrollListParams]'s query parameters as `url.Values`.
func (r PayrollListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type PayrollListPaychecksParams struct {
	// The maximum number of paychecks to return, from 1 to 50.
	Limit param.Field[string] `query:"limit" api:"required"`
	// Return paychecks after this paycheck ID in the stable cursor order. Cannot be
	// used with beforeId.
	AfterID param.Field[string] `query:"afterId"`
	// Return paychecks before this paycheck ID in the stable cursor order. Cannot be
	// used with afterId.
	BeforeID param.Field[string] `query:"beforeId"`
	// Paycheck compensation currencies to include.
	CompensationCurrencies param.Field[[]PublicPayrollCurrency] `query:"compensationCurrencies"`
	// Pay cadences to include.
	PayFrequencies param.Field[[]PublicPayFrequency] `query:"payFrequencies"`
	// Exclusive end of the half-open payday range.
	PaydayBefore param.Field[string] `query:"paydayBefore"`
	// Inclusive start of the half-open payday range.
	PaydayOnOrAfter param.Field[string] `query:"paydayOnOrAfter"`
	// Payment methods to include.
	PaymentMethods param.Field[[]PublicPaycheckPaymentMethod] `query:"paymentMethods"`
	// Payrolls whose paychecks should be included.
	PayrollIDs param.Field[[]string] `query:"payrollIds"`
	// Payroll calculation types to include, subject to the API key permissions.
	PayrollTypes param.Field[[]PublicPayrollType] `query:"payrollTypes"`
	// Lifecycle statuses to include. Omit to include every status.
	Statuses param.Field[[]PublicPaycheckStatus] `query:"statuses"`
	// Workers whose paychecks should be included.
	WorkerIDs param.Field[[]string] `query:"workerIds"`
	// Worker classifications in effect for the paycheck to include. Omit to include
	// every worker type visible to the API key.
	WorkerTypes param.Field[[]PayrollListPaychecksParamsWorkerType] `query:"workerTypes"`
}

// URLQuery serializes [PayrollListPaychecksParams]'s query parameters as `url.Values`.
func (r PayrollListPaychecksParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type PayrollListPaychecksParamsWorkerType string

const (
	PayrollListPaychecksParamsWorkerTypeUsW2             PayrollListPaychecksParamsWorkerType = "us_w2"
	PayrollListPaychecksParamsWorkerTypeUs1099           PayrollListPaychecksParamsWorkerType = "us_1099"
	PayrollListPaychecksParamsWorkerTypeGlobalContractor PayrollListPaychecksParamsWorkerType = "global_contractor"
	PayrollListPaychecksParamsWorkerTypeGlobalEmployee   PayrollListPaychecksParamsWorkerType = "global_employee"
)

func (r PayrollListPaychecksParamsWorkerType) IsKnown() bool {
	switch r {
	case PayrollListPaychecksParamsWorkerTypeUsW2, PayrollListPaychecksParamsWorkerTypeUs1099, PayrollListPaychecksParamsWorkerTypeGlobalContractor, PayrollListPaychecksParamsWorkerTypeGlobalEmployee:
		return true
	}
	return false
}
