// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/TeamWarp/warp-go-sdk/internal/apijson"
	"github.com/TeamWarp/warp-go-sdk/internal/apiquery"
	"github.com/TeamWarp/warp-go-sdk/internal/param"
	"github.com/TeamWarp/warp-go-sdk/internal/requestconfig"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// PayRateService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewPayRateService] method instead.
type PayRateService struct {
	Options []option.RequestOption
}

// NewPayRateService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewPayRateService(opts ...option.RequestOption) (r *PayRateService) {
	r = &PayRateService{}
	r.Options = opts
	return
}

// List pay rates visible to the API key. Results may be filtered by worker, effective start date, or regular/additional type. US and global worker rates require their corresponding compensation read scopes.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: PayRateListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PayRateListResponse: Success
//
// Example:
//
//	payRate, err := client.PayRates.List(context.Background(), sdk.PayRateListParams{
//		Limit: sdk.F[string]("limit"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payRate)
func (r *PayRateService) List(ctx context.Context, query PayRateListParams, opts ...option.RequestOption) (res *PayRateListResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/pay_rates"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get a specific pay rate by id. The API key must have the compensation read scope corresponding to the worker.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: The tag of the pay rate.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PublicPayRate: A regular or additional pay rate assigned to a worker.
//
// Example:
//
//	payRate, err := client.PayRates.Get(context.Background(), "pyr_1234")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payRate)
func (r *PayRateService) Get(ctx context.Context, id string, opts ...option.RequestOption) (res *PublicPayRate, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/pay_rates/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type PublicPayRate struct {
	// The pay rate id.
	ID string `json:"id" api:"required"`
	// Basic identifying information for a worker associated with another resource.
	Worker PublicWorkerReference `json:"worker" api:"required"`
	// Whether the rate is the worker's regular base compensation or an additional rate
	// such as a bonus, commission, or stipend.
	Type PublicPayRateType `json:"type" api:"required"`
	// The period represented by the pay rate amount.
	Per PublicPayRatePer `json:"per" api:"required"`
	// Amount in the currency base unit, e.g. cents for USD.
	Amount   int64                 `json:"amount" api:"required"`
	Currency PublicPayRateCurrency `json:"currency" api:"required"`
	// The server-formatted pay rate, including its period.
	Display string `json:"display" api:"required"`
	// The first date on which the rate applies. Additional rates may have no start
	// date.
	EffectiveStartDate string `json:"effectiveStartDate" api:"required,nullable"`
	// The first date on which the rate no longer applies, or null when it is
	// open-ended.
	EffectiveEndDate string `json:"effectiveEndDate" api:"required,nullable"`
	// A human-readable label for the pay rate, when one is configured.
	Description string            `json:"description" api:"required,nullable"`
	JSON        publicPayRateJSON `json:"-"`
}

// publicPayRateJSON contains the JSON metadata for the struct [PublicPayRate]
type publicPayRateJSON struct {
	ID                 apijson.Field
	Worker             apijson.Field
	Type               apijson.Field
	Per                apijson.Field
	Amount             apijson.Field
	Currency           apijson.Field
	Display            apijson.Field
	EffectiveStartDate apijson.Field
	EffectiveEndDate   apijson.Field
	Description        apijson.Field
	raw                string
	ExtraFields        map[string]apijson.Field
}

func (r *PublicPayRate) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayRateJSON) RawJSON() string {
	return r.raw
}

type PublicPayRateCurrency string

const (
	PublicPayRateCurrencyUsd PublicPayRateCurrency = "USD"
	PublicPayRateCurrencyAud PublicPayRateCurrency = "AUD"
	PublicPayRateCurrencyBgn PublicPayRateCurrency = "BGN"
	PublicPayRateCurrencyBrl PublicPayRateCurrency = "BRL"
	PublicPayRateCurrencyCad PublicPayRateCurrency = "CAD"
	PublicPayRateCurrencyChf PublicPayRateCurrency = "CHF"
	PublicPayRateCurrencyCzk PublicPayRateCurrency = "CZK"
	PublicPayRateCurrencyDkk PublicPayRateCurrency = "DKK"
	PublicPayRateCurrencyEur PublicPayRateCurrency = "EUR"
	PublicPayRateCurrencyGbp PublicPayRateCurrency = "GBP"
	PublicPayRateCurrencyHkd PublicPayRateCurrency = "HKD"
	PublicPayRateCurrencyHuf PublicPayRateCurrency = "HUF"
	PublicPayRateCurrencyIdr PublicPayRateCurrency = "IDR"
	PublicPayRateCurrencyInr PublicPayRateCurrency = "INR"
	PublicPayRateCurrencyJpy PublicPayRateCurrency = "JPY"
	PublicPayRateCurrencyMyr PublicPayRateCurrency = "MYR"
	PublicPayRateCurrencyNok PublicPayRateCurrency = "NOK"
	PublicPayRateCurrencyNzd PublicPayRateCurrency = "NZD"
	PublicPayRateCurrencyCny PublicPayRateCurrency = "CNY"
	PublicPayRateCurrencyPln PublicPayRateCurrency = "PLN"
	PublicPayRateCurrencyRon PublicPayRateCurrency = "RON"
	PublicPayRateCurrencyTry PublicPayRateCurrency = "TRY"
	PublicPayRateCurrencySek PublicPayRateCurrency = "SEK"
	PublicPayRateCurrencySgd PublicPayRateCurrency = "SGD"
	PublicPayRateCurrencyAed PublicPayRateCurrency = "AED"
	PublicPayRateCurrencyArs PublicPayRateCurrency = "ARS"
	PublicPayRateCurrencyBdt PublicPayRateCurrency = "BDT"
	PublicPayRateCurrencyBwp PublicPayRateCurrency = "BWP"
	PublicPayRateCurrencyClp PublicPayRateCurrency = "CLP"
	PublicPayRateCurrencyCop PublicPayRateCurrency = "COP"
	PublicPayRateCurrencyCrc PublicPayRateCurrency = "CRC"
	PublicPayRateCurrencyEgp PublicPayRateCurrency = "EGP"
	PublicPayRateCurrencyFjd PublicPayRateCurrency = "FJD"
	PublicPayRateCurrencyGel PublicPayRateCurrency = "GEL"
	PublicPayRateCurrencyGhs PublicPayRateCurrency = "GHS"
	PublicPayRateCurrencyIls PublicPayRateCurrency = "ILS"
	PublicPayRateCurrencyKes PublicPayRateCurrency = "KES"
	PublicPayRateCurrencyKrw PublicPayRateCurrency = "KRW"
	PublicPayRateCurrencyLkr PublicPayRateCurrency = "LKR"
	PublicPayRateCurrencyMad PublicPayRateCurrency = "MAD"
	PublicPayRateCurrencyMxn PublicPayRateCurrency = "MXN"
	PublicPayRateCurrencyNpr PublicPayRateCurrency = "NPR"
	PublicPayRateCurrencyPhp PublicPayRateCurrency = "PHP"
	PublicPayRateCurrencyPkr PublicPayRateCurrency = "PKR"
	PublicPayRateCurrencyThb PublicPayRateCurrency = "THB"
	PublicPayRateCurrencyUah PublicPayRateCurrency = "UAH"
	PublicPayRateCurrencyUgx PublicPayRateCurrency = "UGX"
	PublicPayRateCurrencyUyu PublicPayRateCurrency = "UYU"
	PublicPayRateCurrencyVnd PublicPayRateCurrency = "VND"
	PublicPayRateCurrencyZar PublicPayRateCurrency = "ZAR"
	PublicPayRateCurrencyZmw PublicPayRateCurrency = "ZMW"
	PublicPayRateCurrencyTnd PublicPayRateCurrency = "TND"
	PublicPayRateCurrencyNgn PublicPayRateCurrency = "NGN"
	PublicPayRateCurrencyRsd PublicPayRateCurrency = "RSD"
	PublicPayRateCurrencyTwd PublicPayRateCurrency = "TWD"
	PublicPayRateCurrencyGtq PublicPayRateCurrency = "GTQ"
	PublicPayRateCurrencyHnl PublicPayRateCurrency = "HNL"
	PublicPayRateCurrencyDop PublicPayRateCurrency = "DOP"
	PublicPayRateCurrencySar PublicPayRateCurrency = "SAR"
	PublicPayRateCurrencyXaf PublicPayRateCurrency = "XAF"
	PublicPayRateCurrencyPen PublicPayRateCurrency = "PEN"
)

func (r PublicPayRateCurrency) IsKnown() bool {
	switch r {
	case PublicPayRateCurrencyUsd, PublicPayRateCurrencyAud, PublicPayRateCurrencyBgn, PublicPayRateCurrencyBrl, PublicPayRateCurrencyCad, PublicPayRateCurrencyChf, PublicPayRateCurrencyCzk, PublicPayRateCurrencyDkk, PublicPayRateCurrencyEur, PublicPayRateCurrencyGbp, PublicPayRateCurrencyHkd, PublicPayRateCurrencyHuf, PublicPayRateCurrencyIdr, PublicPayRateCurrencyInr, PublicPayRateCurrencyJpy, PublicPayRateCurrencyMyr, PublicPayRateCurrencyNok, PublicPayRateCurrencyNzd, PublicPayRateCurrencyCny, PublicPayRateCurrencyPln, PublicPayRateCurrencyRon, PublicPayRateCurrencyTry, PublicPayRateCurrencySek, PublicPayRateCurrencySgd, PublicPayRateCurrencyAed, PublicPayRateCurrencyArs, PublicPayRateCurrencyBdt, PublicPayRateCurrencyBwp, PublicPayRateCurrencyClp, PublicPayRateCurrencyCop, PublicPayRateCurrencyCrc, PublicPayRateCurrencyEgp, PublicPayRateCurrencyFjd, PublicPayRateCurrencyGel, PublicPayRateCurrencyGhs, PublicPayRateCurrencyIls, PublicPayRateCurrencyKes, PublicPayRateCurrencyKrw, PublicPayRateCurrencyLkr, PublicPayRateCurrencyMad, PublicPayRateCurrencyMxn, PublicPayRateCurrencyNpr, PublicPayRateCurrencyPhp, PublicPayRateCurrencyPkr, PublicPayRateCurrencyThb, PublicPayRateCurrencyUah, PublicPayRateCurrencyUgx, PublicPayRateCurrencyUyu, PublicPayRateCurrencyVnd, PublicPayRateCurrencyZar, PublicPayRateCurrencyZmw, PublicPayRateCurrencyTnd, PublicPayRateCurrencyNgn, PublicPayRateCurrencyRsd, PublicPayRateCurrencyTwd, PublicPayRateCurrencyGtq, PublicPayRateCurrencyHnl, PublicPayRateCurrencyDop, PublicPayRateCurrencySar, PublicPayRateCurrencyXaf, PublicPayRateCurrencyPen:
		return true
	}
	return false
}

type PublicPayRateType string

const (
	PublicPayRateTypeRegular    PublicPayRateType = "regular"
	PublicPayRateTypeAdditional PublicPayRateType = "additional"
)

func (r PublicPayRateType) IsKnown() bool {
	switch r {
	case PublicPayRateTypeRegular, PublicPayRateTypeAdditional:
		return true
	}
	return false
}

type PublicPayRatePer string

const (
	PublicPayRatePerYear  PublicPayRatePer = "year"
	PublicPayRatePerMonth PublicPayRatePer = "month"
	PublicPayRatePerWeek  PublicPayRatePer = "week"
	PublicPayRatePerHour  PublicPayRatePer = "hour"
)

func (r PublicPayRatePer) IsKnown() bool {
	switch r {
	case PublicPayRatePerYear, PublicPayRatePerMonth, PublicPayRatePerWeek, PublicPayRatePerHour:
		return true
	}
	return false
}

type PayRateListParams struct {
	Limit param.Field[string] `query:"limit" api:"required"`
	// The tag of the pay rate.
	AfterID param.Field[string] `query:"afterId"`
	// The tag of the pay rate.
	BeforeID param.Field[string] `query:"beforeId"`
	// Only return pay rates whose effective start date is before this date.
	EffectiveBefore param.Field[string] `query:"effectiveBefore"`
	// Only return pay rates whose effective start date is on or after this date.
	EffectiveOnOrAfter param.Field[string] `query:"effectiveOnOrAfter"`
	// Only return regular or additional pay rates of this type.
	Type param.Field[PublicPayRateType] `query:"type"`
	// Only return pay rates assigned to this worker.
	WorkerID param.Field[string] `query:"workerId"`
}

// URLQuery serializes [PayRateListParams]'s query parameters as `url.Values`.
func (r PayRateListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type PayRateListResponse struct {
	HasMore bool                    `json:"hasMore" api:"required"`
	Count   int64                   `json:"count" api:"required"`
	Data    []PublicPayRate         `json:"data" api:"required"`
	JSON    payRateListResponseJSON `json:"-"`
}

// payRateListResponseJSON contains the JSON metadata for the struct [PayRateListResponse]
type payRateListResponseJSON struct {
	HasMore     apijson.Field
	Count       apijson.Field
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PayRateListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r payRateListResponseJSON) RawJSON() string {
	return r.raw
}
