// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"context"
	"net/http"
	"net/url"
	"slices"

	"github.com/TeamWarp/warp-go-sdk/internal/apijson"
	"github.com/TeamWarp/warp-go-sdk/internal/apiquery"
	"github.com/TeamWarp/warp-go-sdk/internal/param"
	"github.com/TeamWarp/warp-go-sdk/internal/requestconfig"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// TimeOffService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewTimeOffService] method instead.
type TimeOffService struct {
	Options  []option.RequestOption
	Policies *TimeOffPolicyService
}

// NewTimeOffService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewTimeOffService(opts ...option.RequestOption) (r *TimeOffService) {
	r = &TimeOffService{}
	r.Options = opts
	r.Policies = NewTimeOffPolicyService(opts...)
	return
}

// Time off assignments are mappings between workers and time off policies. Useful for finding out which policies a worker is assigned to, or which workers are assigned to a given policy.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: TimeOffListAssignmentsParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*TimeOffListAssignmentsResponse: Success
//
// Example:
//
//	timeOff, err := client.TimeOff.ListAssignments(context.Background(), sdk.TimeOffListAssignmentsParams{
//		Limit: sdk.F[string]("limit"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(timeOff)
func (r *TimeOffService) ListAssignments(ctx context.Context, query TimeOffListAssignmentsParams, opts ...option.RequestOption) (res *TimeOffListAssignmentsResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/time_off/assignments"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get worker remaining time-off balances.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: TimeOffListBalancesParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*TimeOffListBalancesResponse: Success
//
// Example:
//
//	timeOff, err := client.TimeOff.ListBalances(context.Background(), sdk.TimeOffListBalancesParams{
//		Limit: sdk.F[string]("limit"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(timeOff)
func (r *TimeOffService) ListBalances(ctx context.Context, query TimeOffListBalancesParams, opts ...option.RequestOption) (res *TimeOffListBalancesResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/time_off/balances"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get the time off requests that workers in your company have made.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: TimeOffListRequestsParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*TimeOffListRequestsResponse: Success
//
// Example:
//
//	timeOff, err := client.TimeOff.ListRequests(context.Background(), sdk.TimeOffListRequestsParams{
//		Limit: sdk.F[string]("limit"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(timeOff)
func (r *TimeOffService) ListRequests(ctx context.Context, query TimeOffListRequestsParams, opts ...option.RequestOption) (res *TimeOffListRequestsResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/time_off/requests"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

type TimeOffListAssignmentsParams struct {
	Limit param.Field[string] `query:"limit" api:"required"`
	// The external-facing id of the worker assignment.
	AfterID param.Field[string] `query:"afterId"`
	// The external-facing id of the worker assignment.
	BeforeID  param.Field[string]   `query:"beforeId"`
	PolicyIDs param.Field[[]string] `query:"policyIds"`
	WorkerIDs param.Field[[]string] `query:"workerIds"`
}

// URLQuery serializes [TimeOffListAssignmentsParams]'s query parameters as `url.Values`.
func (r TimeOffListAssignmentsParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type TimeOffListBalancesParams struct {
	Limit param.Field[string] `query:"limit" api:"required"`
	// The external-facing id of the worker assignment.
	AfterID param.Field[string] `query:"afterId"`
	// The external-facing id of the worker assignment.
	BeforeID  param.Field[string]   `query:"beforeId"`
	EndDate   param.Field[string]   `query:"endDate"`
	PolicyIDs param.Field[[]string] `query:"policyIds"`
	StartDate param.Field[string]   `query:"startDate"`
	WorkerIDs param.Field[[]string] `query:"workerIds"`
}

// URLQuery serializes [TimeOffListBalancesParams]'s query parameters as `url.Values`.
func (r TimeOffListBalancesParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type TimeOffListRequestsParams struct {
	Limit           param.Field[string]                            `query:"limit" api:"required"`
	AfterID         param.Field[string]                            `query:"afterId"`
	BeforeID        param.Field[string]                            `query:"beforeId"`
	EndsBefore      param.Field[string]                            `query:"endsBefore"`
	EndsOnOrAfter   param.Field[string]                            `query:"endsOnOrAfter"`
	PolicyIDs       param.Field[[]string]                          `query:"policyIds"`
	StartsBefore    param.Field[string]                            `query:"startsBefore"`
	StartsOnOrAfter param.Field[string]                            `query:"startsOnOrAfter"`
	Statuses        param.Field[[]TimeOffListRequestsParamsStatus] `query:"statuses"`
	WorkerIDs       param.Field[[]string]                          `query:"workerIds"`
}

// URLQuery serializes [TimeOffListRequestsParams]'s query parameters as `url.Values`.
func (r TimeOffListRequestsParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type TimeOffListRequestsParamsStatus string

const (
	TimeOffListRequestsParamsStatusPending  TimeOffListRequestsParamsStatus = "pending"
	TimeOffListRequestsParamsStatusApproved TimeOffListRequestsParamsStatus = "approved"
	TimeOffListRequestsParamsStatusDenied   TimeOffListRequestsParamsStatus = "denied"
)

func (r TimeOffListRequestsParamsStatus) IsKnown() bool {
	switch r {
	case TimeOffListRequestsParamsStatusPending, TimeOffListRequestsParamsStatusApproved, TimeOffListRequestsParamsStatusDenied:
		return true
	}
	return false
}

type TimeOffListAssignmentsResponse struct {
	HasMore bool                                 `json:"hasMore" api:"required"`
	Count   int64                                `json:"count" api:"required"`
	Data    []TimeOffListAssignmentsResponseData `json:"data" api:"required"`
	JSON    timeOffListAssignmentsResponseJSON   `json:"-"`
}

// timeOffListAssignmentsResponseJSON contains the JSON metadata for the struct [TimeOffListAssignmentsResponse]
type timeOffListAssignmentsResponseJSON struct {
	HasMore     apijson.Field
	Count       apijson.Field
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TimeOffListAssignmentsResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r timeOffListAssignmentsResponseJSON) RawJSON() string {
	return r.raw
}

type TimeOffListBalancesResponse struct {
	HasMore bool                              `json:"hasMore" api:"required"`
	Count   int64                             `json:"count" api:"required"`
	Data    []TimeOffListBalancesResponseData `json:"data" api:"required"`
	JSON    timeOffListBalancesResponseJSON   `json:"-"`
}

// timeOffListBalancesResponseJSON contains the JSON metadata for the struct [TimeOffListBalancesResponse]
type timeOffListBalancesResponseJSON struct {
	HasMore     apijson.Field
	Count       apijson.Field
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TimeOffListBalancesResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r timeOffListBalancesResponseJSON) RawJSON() string {
	return r.raw
}

type TimeOffListRequestsResponse struct {
	HasMore bool                              `json:"hasMore" api:"required"`
	Count   int64                             `json:"count" api:"required"`
	Data    []TimeOffListRequestsResponseData `json:"data" api:"required"`
	JSON    timeOffListRequestsResponseJSON   `json:"-"`
}

// timeOffListRequestsResponseJSON contains the JSON metadata for the struct [TimeOffListRequestsResponse]
type timeOffListRequestsResponseJSON struct {
	HasMore     apijson.Field
	Count       apijson.Field
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TimeOffListRequestsResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r timeOffListRequestsResponseJSON) RawJSON() string {
	return r.raw
}

type TimeOffListAssignmentsResponseData struct {
	// The external-facing id of the worker assignment.
	ID       string `json:"id" api:"required"`
	PolicyID string `json:"policyId" api:"required"`
	// The id of the worker.
	WorkerID   string                                 `json:"workerId" api:"required"`
	AssignedAt string                                 `json:"assignedAt" api:"required"`
	JSON       timeOffListAssignmentsResponseDataJSON `json:"-"`
}

// timeOffListAssignmentsResponseDataJSON contains the JSON metadata for the struct [TimeOffListAssignmentsResponseData]
type timeOffListAssignmentsResponseDataJSON struct {
	ID          apijson.Field
	PolicyID    apijson.Field
	WorkerID    apijson.Field
	AssignedAt  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TimeOffListAssignmentsResponseData) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r timeOffListAssignmentsResponseDataJSON) RawJSON() string {
	return r.raw
}

type TimeOffListBalancesResponseData struct {
	// The external-facing id of the worker assignment.
	ID              string                              `json:"id" api:"required"`
	PolicyID        string                              `json:"policyId" api:"required"`
	LegacyWorkerID  string                              `json:"legacyWorkerId" api:"required"`
	AccruedUnlocked interface{}                         `json:"accruedUnlocked" api:"required"`
	AccruedLocked   interface{}                         `json:"accruedLocked" api:"required"`
	Used            interface{}                         `json:"used" api:"required"`
	Holds           interface{}                         `json:"holds" api:"required"`
	Available       interface{}                         `json:"available" api:"required"`
	JSON            timeOffListBalancesResponseDataJSON `json:"-"`
}

// timeOffListBalancesResponseDataJSON contains the JSON metadata for the struct [TimeOffListBalancesResponseData]
type timeOffListBalancesResponseDataJSON struct {
	ID              apijson.Field
	PolicyID        apijson.Field
	LegacyWorkerID  apijson.Field
	AccruedUnlocked apijson.Field
	AccruedLocked   apijson.Field
	Used            apijson.Field
	Holds           apijson.Field
	Available       apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *TimeOffListBalancesResponseData) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r timeOffListBalancesResponseDataJSON) RawJSON() string {
	return r.raw
}

type TimeOffListRequestsResponseData struct {
	ID              string `json:"id" api:"required"`
	TimeOffPolicyID string `json:"timeOffPolicyId" api:"required"`
	// The id of the worker.
	WorkerID         string                                        `json:"workerId" api:"required"`
	Status           TimeOffListRequestsResponseDataStatus         `json:"status" api:"required"`
	StartAt          string                                        `json:"startAt" api:"required"`
	StartRangeType   TimeOffListRequestsResponseDataStartRangeType `json:"startRangeType" api:"required"`
	EndAt            string                                        `json:"endAt" api:"required"`
	EndRangeType     TimeOffListRequestsResponseDataEndRangeType   `json:"endRangeType" api:"required"`
	Reason           string                                        `json:"reason" api:"required,nullable"`
	CreatedAt        string                                        `json:"createdAt" api:"required"`
	RequestedMinutes interface{}                                   `json:"requestedMinutes" api:"required"`
	// The time zone that the worker is requesting time off in.
	TimeZone string                              `json:"timeZone" api:"required,nullable"`
	JSON     timeOffListRequestsResponseDataJSON `json:"-"`
}

// timeOffListRequestsResponseDataJSON contains the JSON metadata for the struct [TimeOffListRequestsResponseData]
type timeOffListRequestsResponseDataJSON struct {
	ID               apijson.Field
	TimeOffPolicyID  apijson.Field
	WorkerID         apijson.Field
	Status           apijson.Field
	StartAt          apijson.Field
	StartRangeType   apijson.Field
	EndAt            apijson.Field
	EndRangeType     apijson.Field
	Reason           apijson.Field
	CreatedAt        apijson.Field
	RequestedMinutes apijson.Field
	TimeZone         apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *TimeOffListRequestsResponseData) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r timeOffListRequestsResponseDataJSON) RawJSON() string {
	return r.raw
}

type TimeOffListRequestsResponseDataStatus string

const (
	TimeOffListRequestsResponseDataStatusPending  TimeOffListRequestsResponseDataStatus = "pending"
	TimeOffListRequestsResponseDataStatusApproved TimeOffListRequestsResponseDataStatus = "approved"
	TimeOffListRequestsResponseDataStatusDenied   TimeOffListRequestsResponseDataStatus = "denied"
)

func (r TimeOffListRequestsResponseDataStatus) IsKnown() bool {
	switch r {
	case TimeOffListRequestsResponseDataStatusPending, TimeOffListRequestsResponseDataStatusApproved, TimeOffListRequestsResponseDataStatusDenied:
		return true
	}
	return false
}

type TimeOffListRequestsResponseDataStartRangeType string

const (
	TimeOffListRequestsResponseDataStartRangeTypeDate     TimeOffListRequestsResponseDataStartRangeType = "date"
	TimeOffListRequestsResponseDataStartRangeTypeDatetime TimeOffListRequestsResponseDataStartRangeType = "datetime"
)

func (r TimeOffListRequestsResponseDataStartRangeType) IsKnown() bool {
	switch r {
	case TimeOffListRequestsResponseDataStartRangeTypeDate, TimeOffListRequestsResponseDataStartRangeTypeDatetime:
		return true
	}
	return false
}

type TimeOffListRequestsResponseDataEndRangeType string

const (
	TimeOffListRequestsResponseDataEndRangeTypeDate     TimeOffListRequestsResponseDataEndRangeType = "date"
	TimeOffListRequestsResponseDataEndRangeTypeDatetime TimeOffListRequestsResponseDataEndRangeType = "datetime"
)

func (r TimeOffListRequestsResponseDataEndRangeType) IsKnown() bool {
	switch r {
	case TimeOffListRequestsResponseDataEndRangeTypeDate, TimeOffListRequestsResponseDataEndRangeTypeDatetime:
		return true
	}
	return false
}
