// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/TeamWarp/warp-go-sdk/internal/apijson"
	"github.com/TeamWarp/warp-go-sdk/internal/apiquery"
	"github.com/TeamWarp/warp-go-sdk/internal/param"
	"github.com/TeamWarp/warp-go-sdk/internal/requestconfig"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// TimeOffPolicyService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewTimeOffPolicyService] method instead.
type TimeOffPolicyService struct {
	Options []option.RequestOption
}

// NewTimeOffPolicyService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewTimeOffPolicyService(opts ...option.RequestOption) (r *TimeOffPolicyService) {
	r = &TimeOffPolicyService{}
	r.Options = opts
	return
}

// Get the time off policies for your company
//
// Parameters:
//
//	ctx: Context for the request.
//	query: TimeOffPolicyListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*TimeOffPolicyListResponse: Success
//
// Example:
//
//	policy, err := client.TimeOff.Policies.List(context.Background(), sdk.TimeOffPolicyListParams{
//		Limit: sdk.F[string]("limit"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(policy)
func (r *TimeOffPolicyService) List(ctx context.Context, query TimeOffPolicyListParams, opts ...option.RequestOption) (res *TimeOffPolicyListResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/time_off/policies"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get a specific time off policy by id
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*TimeOffPolicyGetResponse: Success
//
// Example:
//
//	policy, err := client.TimeOff.Policies.Get(context.Background(), "top_1234")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(policy)
func (r *TimeOffPolicyService) Get(ctx context.Context, id string, opts ...option.RequestOption) (res *TimeOffPolicyGetResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/time_off/policies/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type TimeOffPolicyListParams struct {
	Limit    param.Field[string] `query:"limit" api:"required"`
	AfterID  param.Field[string] `query:"afterId"`
	BeforeID param.Field[string] `query:"beforeId"`
}

// URLQuery serializes [TimeOffPolicyListParams]'s query parameters as `url.Values`.
func (r TimeOffPolicyListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type TimeOffPolicyListResponse struct {
	Count   int64                           `json:"count" api:"required"`
	Data    []TimeOffPolicyListResponseData `json:"data" api:"required"`
	HasMore bool                            `json:"hasMore" api:"required"`
	JSON    timeOffPolicyListResponseJSON   `json:"-"`
}

// timeOffPolicyListResponseJSON contains the JSON metadata for the struct [TimeOffPolicyListResponse]
type timeOffPolicyListResponseJSON struct {
	Count       apijson.Field
	Data        apijson.Field
	HasMore     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TimeOffPolicyListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r timeOffPolicyListResponseJSON) RawJSON() string {
	return r.raw
}

type TimeOffPolicyGetResponse struct {
	ID                  string                           `json:"id" api:"required"`
	Description         string                           `json:"description" api:"required,nullable"`
	HoursWorkedPerChunk interface{}                      `json:"hoursWorkedPerChunk" api:"required,nullable"`
	IsUnlimited         bool                             `json:"isUnlimited" api:"required"`
	MinutesPerChunk     interface{}                      `json:"minutesPerChunk" api:"required,nullable"`
	MinutesPerPeriod    interface{}                      `json:"minutesPerPeriod" api:"required,nullable"`
	Name                string                           `json:"name" api:"required"`
	Paid                bool                             `json:"paid" api:"required"`
	Schedule            TimeOffPolicyGetResponseSchedule `json:"schedule" api:"required"`
	TimeOffTypeID       string                           `json:"timeOffTypeId" api:"required"`
	TimeOffTypeName     string                           `json:"timeOffTypeName" api:"required"`
	Unit                TimeOffPolicyGetResponseUnit     `json:"unit" api:"required"`
	JSON                timeOffPolicyGetResponseJSON     `json:"-"`
}

// timeOffPolicyGetResponseJSON contains the JSON metadata for the struct [TimeOffPolicyGetResponse]
type timeOffPolicyGetResponseJSON struct {
	ID                  apijson.Field
	Description         apijson.Field
	HoursWorkedPerChunk apijson.Field
	IsUnlimited         apijson.Field
	MinutesPerChunk     apijson.Field
	MinutesPerPeriod    apijson.Field
	Name                apijson.Field
	Paid                apijson.Field
	Schedule            apijson.Field
	TimeOffTypeID       apijson.Field
	TimeOffTypeName     apijson.Field
	Unit                apijson.Field
	raw                 string
	ExtraFields         map[string]apijson.Field
}

func (r *TimeOffPolicyGetResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r timeOffPolicyGetResponseJSON) RawJSON() string {
	return r.raw
}

type TimeOffPolicyListResponseData struct {
	ID                  string                                `json:"id" api:"required"`
	Description         string                                `json:"description" api:"required,nullable"`
	HoursWorkedPerChunk interface{}                           `json:"hoursWorkedPerChunk" api:"required,nullable"`
	IsUnlimited         bool                                  `json:"isUnlimited" api:"required"`
	MinutesPerChunk     interface{}                           `json:"minutesPerChunk" api:"required,nullable"`
	MinutesPerPeriod    interface{}                           `json:"minutesPerPeriod" api:"required,nullable"`
	Name                string                                `json:"name" api:"required"`
	Paid                bool                                  `json:"paid" api:"required"`
	Schedule            TimeOffPolicyListResponseDataSchedule `json:"schedule" api:"required"`
	TimeOffTypeID       string                                `json:"timeOffTypeId" api:"required"`
	TimeOffTypeName     string                                `json:"timeOffTypeName" api:"required"`
	Unit                TimeOffPolicyListResponseDataUnit     `json:"unit" api:"required"`
	JSON                timeOffPolicyListResponseDataJSON     `json:"-"`
}

// timeOffPolicyListResponseDataJSON contains the JSON metadata for the struct [TimeOffPolicyListResponseData]
type timeOffPolicyListResponseDataJSON struct {
	ID                  apijson.Field
	Description         apijson.Field
	HoursWorkedPerChunk apijson.Field
	IsUnlimited         apijson.Field
	MinutesPerChunk     apijson.Field
	MinutesPerPeriod    apijson.Field
	Name                apijson.Field
	Paid                apijson.Field
	Schedule            apijson.Field
	TimeOffTypeID       apijson.Field
	TimeOffTypeName     apijson.Field
	Unit                apijson.Field
	raw                 string
	ExtraFields         map[string]apijson.Field
}

func (r *TimeOffPolicyListResponseData) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r timeOffPolicyListResponseDataJSON) RawJSON() string {
	return r.raw
}

type TimeOffPolicyGetResponseSchedule string

const (
	TimeOffPolicyGetResponseSchedulePerHourWorked TimeOffPolicyGetResponseSchedule = "per_hour_worked"
	TimeOffPolicyGetResponseScheduleMonthly       TimeOffPolicyGetResponseSchedule = "monthly"
	TimeOffPolicyGetResponseScheduleYearly        TimeOffPolicyGetResponseSchedule = "yearly"
	TimeOffPolicyGetResponseScheduleUnlimited     TimeOffPolicyGetResponseSchedule = "unlimited"
)

func (r TimeOffPolicyGetResponseSchedule) IsKnown() bool {
	switch r {
	case TimeOffPolicyGetResponseSchedulePerHourWorked, TimeOffPolicyGetResponseScheduleMonthly, TimeOffPolicyGetResponseScheduleYearly, TimeOffPolicyGetResponseScheduleUnlimited:
		return true
	}
	return false
}

type TimeOffPolicyGetResponseUnit string

const (
	TimeOffPolicyGetResponseUnitHour TimeOffPolicyGetResponseUnit = "hour"
	TimeOffPolicyGetResponseUnitDay  TimeOffPolicyGetResponseUnit = "day"
)

func (r TimeOffPolicyGetResponseUnit) IsKnown() bool {
	switch r {
	case TimeOffPolicyGetResponseUnitHour, TimeOffPolicyGetResponseUnitDay:
		return true
	}
	return false
}

type TimeOffPolicyListResponseDataSchedule string

const (
	TimeOffPolicyListResponseDataSchedulePerHourWorked TimeOffPolicyListResponseDataSchedule = "per_hour_worked"
	TimeOffPolicyListResponseDataScheduleMonthly       TimeOffPolicyListResponseDataSchedule = "monthly"
	TimeOffPolicyListResponseDataScheduleYearly        TimeOffPolicyListResponseDataSchedule = "yearly"
	TimeOffPolicyListResponseDataScheduleUnlimited     TimeOffPolicyListResponseDataSchedule = "unlimited"
)

func (r TimeOffPolicyListResponseDataSchedule) IsKnown() bool {
	switch r {
	case TimeOffPolicyListResponseDataSchedulePerHourWorked, TimeOffPolicyListResponseDataScheduleMonthly, TimeOffPolicyListResponseDataScheduleYearly, TimeOffPolicyListResponseDataScheduleUnlimited:
		return true
	}
	return false
}

type TimeOffPolicyListResponseDataUnit string

const (
	TimeOffPolicyListResponseDataUnitHour TimeOffPolicyListResponseDataUnit = "hour"
	TimeOffPolicyListResponseDataUnitDay  TimeOffPolicyListResponseDataUnit = "day"
)

func (r TimeOffPolicyListResponseDataUnit) IsKnown() bool {
	switch r {
	case TimeOffPolicyListResponseDataUnitHour, TimeOffPolicyListResponseDataUnitDay:
		return true
	}
	return false
}
