// Code generated by Scalar SDK Generator. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"strings"
	"sync"
	"time"

	sdk "github.com/TeamWarp/warp-go-sdk"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// Smoke test: calls every generated operation once to confirm the SDK can reach each endpoint.
// Run it from this repo with `go run tests/smoke-test.go`. The generator also runs this file
// against a mock server and reads the JSON report produced via SCALAR_SMOKE_REPORT.
var client = sdk.NewClient(option.WithAPIKey("test"), option.WithHeader("x-api-key", "test"))

type smokeResult struct {
	Operation  string `json:"operation"`
	Method     string `json:"method"`
	Path       string `json:"path"`
	Label      string `json:"label,omitempty"`
	Status     string `json:"status"`
	DurationMs int64  `json:"durationMs"`
	Error      string `json:"error,omitempty"`
}

// Label says which of an operation's two calls this is — "required params" or "all params".
// It is empty when the operation contributed a single case.
type smokeCase struct {
	Operation string
	Method    string
	Path      string
	Label     string
	Run       func()
}

func _smokeCase0() {
	healthPlan, err := client.Benefits.HealthPlans.List(context.Background(), sdk.BenefitHealthPlanListParams{
		Limit:    sdk.F[string]("limit"),
		Statuses: sdk.F[[]sdk.PublicHealthPlanStatus]([]sdk.PublicHealthPlanStatus{"active"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(healthPlan)
}

func _smokeCase1() {
	healthPlan, err := client.Benefits.HealthPlans.List(context.Background(), sdk.BenefitHealthPlanListParams{
		Limit:      sdk.F[string]("limit"),
		Statuses:   sdk.F[[]sdk.PublicHealthPlanStatus]([]sdk.PublicHealthPlanStatus{"active"}),
		AfterID:    sdk.F[string]("chpl_1234"),
		BeforeID:   sdk.F[string]("chpl_1234"),
		CarrierIDs: sdk.F[[]string]([]string{"car_1234"}),
		Types:      sdk.F[[]sdk.BenefitHealthPlanListParamsType]([]sdk.BenefitHealthPlanListParamsType{"medical"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(healthPlan)
}

func _smokeCase2() {
	healthPlan, err := client.Benefits.HealthPlans.Get(context.Background(), "chpl_1234")
	if err != nil {
		panic(err)
	}

	fmt.Println(healthPlan)
}

func _smokeCase3() {
	retirementPlan, err := client.Benefits.RetirementPlans.List(context.Background(), sdk.BenefitRetirementPlanListParams{
		Limit:    sdk.F[string]("limit"),
		Statuses: sdk.F[[]sdk.PublicRetirementPlanStatus]([]sdk.PublicRetirementPlanStatus{"active"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(retirementPlan)
}

func _smokeCase4() {
	retirementPlan, err := client.Benefits.RetirementPlans.List(context.Background(), sdk.BenefitRetirementPlanListParams{
		Limit:    sdk.F[string]("limit"),
		Statuses: sdk.F[[]sdk.PublicRetirementPlanStatus]([]sdk.PublicRetirementPlanStatus{"active"}),
		AfterID:  sdk.F[string]("crpl_1234"),
		BeforeID: sdk.F[string]("crpl_1234"),
		Types:    sdk.F[[]sdk.BenefitRetirementPlanListParamsType]([]sdk.BenefitRetirementPlanListParamsType{"401k"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(retirementPlan)
}

func _smokeCase5() {
	retirementPlan, err := client.Benefits.RetirementPlans.Get(context.Background(), "crpl_1234")
	if err != nil {
		panic(err)
	}

	fmt.Println(retirementPlan)
}

func _smokeCase6() {
	deduction, err := client.Benefits.Deductions.List(context.Background(), sdk.BenefitDeductionListParams{
		Limit:    sdk.F[string]("limit"),
		Statuses: sdk.F[[]sdk.PublicBenefitDeductionStatus]([]sdk.PublicBenefitDeductionStatus{"active"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(deduction)
}

func _smokeCase7() {
	deduction, err := client.Benefits.Deductions.List(context.Background(), sdk.BenefitDeductionListParams{
		Limit:             sdk.F[string]("limit"),
		Statuses:          sdk.F[[]sdk.PublicBenefitDeductionStatus]([]sdk.PublicBenefitDeductionStatus{"active"}),
		AfterID:           sdk.F[string]("pbdg_1234"),
		BeforeID:          sdk.F[string]("pbdg_1234"),
		Categories:        sdk.F[[]sdk.PublicBenefitDeductionCategory]([]sdk.PublicBenefitDeductionCategory{"health"}),
		HealthPlanIDs:     sdk.F[[]string]([]string{"chpl_1234"}),
		RetirementPlanIDs: sdk.F[[]string]([]string{"crpl_1234"}),
		Types:             sdk.F[[]sdk.BenefitDeductionListParamsType]([]sdk.BenefitDeductionListParamsType{"medical"}),
		WorkerIDs:         sdk.F[[]string]([]string{"wrk_1234"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(deduction)
}

func _smokeCase8() {
	deduction, err := client.Benefits.Deductions.Get(context.Background(), "pbdg_1234")
	if err != nil {
		panic(err)
	}

	fmt.Println(deduction)
}

func _smokeCase9() {
	customField, err := client.CustomFields.List(context.Background())
	if err != nil {
		panic(err)
	}

	fmt.Println(customField)
}

func _smokeCase10() {
	customField, err := client.CustomFields.New(context.Background(), sdk.CustomFieldNewParams{
		Category: sdk.F[sdk.CustomFieldNewParamsCategory](sdk.CustomFieldNewParamsCategory("info")),
		Name:     sdk.F[string]("x"),
		Type:     sdk.F[sdk.CustomFieldNewParamsType](sdk.CustomFieldNewParamsType("text")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customField)
}

func _smokeCase11() {
	customField, err := client.CustomFields.New(context.Background(), sdk.CustomFieldNewParams{
		Category:    sdk.F[sdk.CustomFieldNewParamsCategory](sdk.CustomFieldNewParamsCategory("info")),
		Name:        sdk.F[string]("x"),
		Type:        sdk.F[sdk.CustomFieldNewParamsType](sdk.CustomFieldNewParamsType("text")),
		AccessLevel: sdk.F[sdk.CustomFieldNewParamsAccessLevel](sdk.CustomFieldNewParamsAccessLevel("admins")),
		Config:      sdk.F[interface{}](map[string]interface{}{}),
		Description: sdk.F[string](""),
		InputBy:     sdk.F[sdk.CustomFieldNewParamsInputBy](sdk.CustomFieldNewParamsInputBy("admin")),
		Options: sdk.F[[]sdk.CustomFieldNewParamsOption]([]sdk.CustomFieldNewParamsOption{sdk.CustomFieldNewParamsOption{
			Label: sdk.F[string]("x"),
			Value: sdk.F[string]("x"),
		}}),
		Required: sdk.F[bool](false),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customField)
}

func _smokeCase12() {
	customField, err := client.CustomFields.Get(context.Background(), "cf_1234")
	if err != nil {
		panic(err)
	}

	fmt.Println(customField)
}

func _smokeCase13() {
	customField, err := client.CustomFields.Update(context.Background(), "cf_1234", sdk.CustomFieldUpdateParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(customField)
}

func _smokeCase14() {
	customField, err := client.CustomFields.Update(context.Background(), "cf_1234", sdk.CustomFieldUpdateParams{
		AccessLevel: sdk.F[sdk.CustomFieldUpdateParamsAccessLevel](sdk.CustomFieldUpdateParamsAccessLevel("admins")),
		Category:    sdk.F[sdk.CustomFieldUpdateParamsCategory](sdk.CustomFieldUpdateParamsCategory("info")),
		Config:      sdk.F[interface{}](map[string]interface{}{}),
		Description: sdk.F[string](""),
		InputBy:     sdk.F[sdk.CustomFieldUpdateParamsInputBy](sdk.CustomFieldUpdateParamsInputBy("admin")),
		Name:        sdk.F[string]("x"),
		Required:    sdk.F[bool](false),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customField)
}

func _smokeCase15() {
	customField, err := client.CustomFields.Archive(context.Background(), "cf_1234")
	if err != nil {
		panic(err)
	}

	fmt.Println(customField)
}

func _smokeCase16() {
	customField, err := client.CustomFields.NewOption(context.Background(), "cf_1234", sdk.CustomFieldNewOptionParams{
		Label: sdk.F[string]("x"),
		Value: sdk.F[string]("x"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customField)
}

func _smokeCase17() {
	customField, err := client.CustomFields.NewOption(context.Background(), "cf_1234", sdk.CustomFieldNewOptionParams{
		Label:     sdk.F[string]("x"),
		Value:     sdk.F[string]("x"),
		SortOrder: sdk.F[interface{}](0),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customField)
}

func _smokeCase18() {
	customField, err := client.CustomFields.UpdateOption(context.Background(), "cfo_1234", sdk.CustomFieldUpdateOptionParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(customField)
}

func _smokeCase19() {
	customField, err := client.CustomFields.UpdateOption(context.Background(), "cfo_1234", sdk.CustomFieldUpdateOptionParams{
		Label:     sdk.F[string]("x"),
		SortOrder: sdk.F[interface{}](0),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customField)
}

func _smokeCase20() {
	err := client.CustomFields.DeleteOption(context.Background(), "cfo_1234")
	if err != nil {
		panic(err)
	}
}

func _smokeCase21() {
	customField, err := client.CustomFields.ArchiveOption(context.Background(), "cfo_1234")
	if err != nil {
		panic(err)
	}

	fmt.Println(customField)
}

func _smokeCase22() {
	customField, err := client.CustomFields.ListValues(context.Background(), sdk.CustomFieldListValuesParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(customField)
}

func _smokeCase23() {
	customField, err := client.CustomFields.ListValues(context.Background(), sdk.CustomFieldListValuesParams{
		FieldIDs:  sdk.F[[]string]([]string{"cf_1234"}),
		WorkerIDs: sdk.F[[]string]([]string{"wrk_1234"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customField)
}

func _smokeCase24() {
	customField, err := client.CustomFields.UpsertValue(context.Background(), sdk.CustomFieldUpsertValueParams{
		FieldID:  sdk.F[string]("cf_1234"),
		Value:    sdk.F[sdk.CustomFieldUpsertValueParamsValueUnion](sdk.CustomFieldUpsertValueParamsValueUnion{}),
		WorkerID: sdk.F[string]("wrk_1234"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customField)
}

func _smokeCase25() {
	err := client.CustomFields.ClearValue(context.Background(), sdk.CustomFieldClearValueParams{
		FieldID:  sdk.F[string]("cf_1234"),
		WorkerID: sdk.F[string]("wrk_1234"),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase26() {
	department, err := client.Departments.List(context.Background(), sdk.DepartmentListParams{
		Limit: sdk.F[string]("limit"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(department)
}

func _smokeCase27() {
	department, err := client.Departments.List(context.Background(), sdk.DepartmentListParams{
		Limit:    sdk.F[string]("limit"),
		AfterID:  sdk.F[string]("dpt_1234"),
		BeforeID: sdk.F[string]("dpt_1234"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(department)
}

func _smokeCase28() {
	department, err := client.Departments.New(context.Background(), sdk.DepartmentNewParams{
		Name: sdk.F[string]("x"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(department)
}

func _smokeCase29() {
	department, err := client.Departments.Update(context.Background(), "dpt_1234", sdk.DepartmentUpdateParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(department)
}

func _smokeCase30() {
	department, err := client.Departments.Update(context.Background(), "dpt_1234", sdk.DepartmentUpdateParams{
		Name: sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(department)
}

func _smokeCase31() {
	level, err := client.Levels.List(context.Background())
	if err != nil {
		panic(err)
	}

	fmt.Println(level)
}

func _smokeCase32() {
	offer, err := client.Offers.List(context.Background(), sdk.OfferListParams{
		Limit: sdk.F[string]("limit"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(offer)
}

func _smokeCase33() {
	offer, err := client.Offers.List(context.Background(), sdk.OfferListParams{
		Limit:          sdk.F[string]("limit"),
		AfterID:        sdk.F[string]("offr_1234"),
		BeforeID:       sdk.F[string]("offr_1234"),
		CandidateEmail: sdk.F[string]("john@joinwarp.com"),
		Statuses:       sdk.F[[]sdk.OfferListParamsStatus]([]sdk.OfferListParamsStatus{"draft"}),
		WorkerTypes:    sdk.F[[]sdk.OfferListParamsWorkerType]([]sdk.OfferListParamsWorkerType{"employee"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(offer)
}

func _smokeCase34() {
	offer, err := client.Offers.New(context.Background(), sdk.OfferNewParams{
		Candidate: sdk.F[sdk.OfferNewParamsCandidate](sdk.OfferNewParamsCandidate{
			FirstName: sdk.F[string]("x"),
			LastName:  sdk.F[string]("x"),
			Email:     sdk.F[string]("john@joinwarp.com"),
		}),
		Compensation: sdk.F[sdk.OfferNewParamsCompensation](sdk.OfferNewParamsCompensation{
			PayBasis:    sdk.F[sdk.OfferNewParamsCompensationPayBasis](sdk.OfferNewParamsCompensationPayBasis("year")),
			PayCurrency: sdk.F[sdk.OfferNewParamsCompensationPayCurrency](sdk.OfferNewParamsCompensationPayCurrency("USD")),
			PayRate:     sdk.F[float64](1),
		}),
		Position: sdk.F[sdk.OfferNewParamsPosition](sdk.OfferNewParamsPosition{
			Title:     sdk.F[string]("x"),
			StartDate: sdk.F[string](""),
		}),
		WorkerType: sdk.F[sdk.OfferNewParamsWorkerType](sdk.OfferNewParamsWorkerType("employee")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(offer)
}

func _smokeCase35() {
	offer, err := client.Offers.New(context.Background(), sdk.OfferNewParams{
		Candidate: sdk.F[sdk.OfferNewParamsCandidate](sdk.OfferNewParamsCandidate{
			FirstName: sdk.F[string]("x"),
			LastName:  sdk.F[string]("x"),
			Email:     sdk.F[string]("john@joinwarp.com"),
		}),
		Compensation: sdk.F[sdk.OfferNewParamsCompensation](sdk.OfferNewParamsCompensation{
			PayBasis:    sdk.F[sdk.OfferNewParamsCompensationPayBasis](sdk.OfferNewParamsCompensationPayBasis("year")),
			PayCurrency: sdk.F[sdk.OfferNewParamsCompensationPayCurrency](sdk.OfferNewParamsCompensationPayCurrency("USD")),
			PayRate:     sdk.F[float64](1),
		}),
		Position: sdk.F[sdk.OfferNewParamsPosition](sdk.OfferNewParamsPosition{
			Title:     sdk.F[string]("x"),
			StartDate: sdk.F[string](""),
		}),
		WorkerType: sdk.F[sdk.OfferNewParamsWorkerType](sdk.OfferNewParamsWorkerType("employee")),
		BackgroundCheckWorkLocation: sdk.F[sdk.OfferNewParamsBackgroundCheckWorkLocation](sdk.OfferNewParamsBackgroundCheckWorkLocation{
			Country: sdk.F[string](""),
			State:   sdk.F[string](""),
			City:    sdk.F[string](""),
		}),
		DepartmentID:   sdk.F[string]("dpt_1234"),
		ExpirationTime: sdk.F[string](""),
		LevelID:        sdk.F[string]("jlvl_1234"),
		ManagerID:      sdk.F[string]("wrk_1234"),
		WorkplaceID:    sdk.F[string]("wkp_1234"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(offer)
}

func _smokeCase36() {
	offer, err := client.Offers.Void(context.Background(), "offr_1234", sdk.OfferVoidParams{
		VoidReason: sdk.F[sdk.OfferVoidParamsVoidReason](sdk.OfferVoidParamsVoidReason("candidate_declined")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(offer)
}

func _smokeCase37() {
	offer, err := client.Offers.Void(context.Background(), "offr_1234", sdk.OfferVoidParams{
		VoidReason: sdk.F[sdk.OfferVoidParamsVoidReason](sdk.OfferVoidParamsVoidReason("candidate_declined")),
		VoidNotes:  sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(offer)
}

func _smokeCase38() {
	offer, err := client.Offers.ExtendDeadline(context.Background(), "offr_1234", sdk.OfferExtendDeadlineParams{
		ExpirationTime: sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(offer)
}

func _smokeCase39() {
	offer, err := client.Offers.Resend(context.Background(), "offr_1234")
	if err != nil {
		panic(err)
	}

	fmt.Println(offer)
}

func _smokeCase40() {
	payRate, err := client.PayRates.List(context.Background(), sdk.PayRateListParams{
		Limit: sdk.F[string]("limit"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payRate)
}

func _smokeCase41() {
	payRate, err := client.PayRates.List(context.Background(), sdk.PayRateListParams{
		Limit:              sdk.F[string]("limit"),
		AfterID:            sdk.F[string]("pyr_1234"),
		BeforeID:           sdk.F[string]("pyr_1234"),
		EffectiveBefore:    sdk.F[string]("effectiveBefore"),
		EffectiveOnOrAfter: sdk.F[string]("effectiveOnOrAfter"),
		Type:               sdk.F[sdk.PublicPayRateType](sdk.PublicPayRateType("regular")),
		WorkerID:           sdk.F[string]("wrk_1234"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payRate)
}

func _smokeCase42() {
	payRate, err := client.PayRates.Get(context.Background(), "pyr_1234")
	if err != nil {
		panic(err)
	}

	fmt.Println(payRate)
}

func _smokeCase43() {
	payroll, err := client.Payroll.List(context.Background(), sdk.PayrollListParams{
		Limit: sdk.F[string]("limit"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payroll)
}

func _smokeCase44() {
	payroll, err := client.Payroll.List(context.Background(), sdk.PayrollListParams{
		Limit:                 sdk.F[string]("limit"),
		AfterID:               sdk.F[string]("pay_1234"),
		BeforeID:              sdk.F[string]("pay_1234"),
		PayFrequencies:        sdk.F[[]sdk.PublicPayFrequency]([]sdk.PublicPayFrequency{"semimonthly"}),
		PayPeriodEndBefore:    sdk.F[string]("payPeriodEndBefore"),
		PayPeriodEndOnOrAfter: sdk.F[string]("payPeriodEndOnOrAfter"),
		PaydayBefore:          sdk.F[string]("paydayBefore"),
		PaydayOnOrAfter:       sdk.F[string]("paydayOnOrAfter"),
		Statuses:              sdk.F[[]sdk.PublicPayrollStatus]([]sdk.PublicPayrollStatus{"processing"}),
		Subtypes:              sdk.F[[]sdk.PublicPayrollSubtype]([]sdk.PublicPayrollSubtype{"regular"}),
		Types:                 sdk.F[[]sdk.PublicPayrollType]([]sdk.PublicPayrollType{"us"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payroll)
}

func _smokeCase45() {
	payroll, err := client.Payroll.Get(context.Background(), "pay_1234")
	if err != nil {
		panic(err)
	}

	fmt.Println(payroll)
}

func _smokeCase46() {
	payroll, err := client.Payroll.ListPaychecks(context.Background(), sdk.PayrollListPaychecksParams{
		Limit: sdk.F[string]("limit"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payroll)
}

func _smokeCase47() {
	payroll, err := client.Payroll.ListPaychecks(context.Background(), sdk.PayrollListPaychecksParams{
		Limit:                  sdk.F[string]("limit"),
		AfterID:                sdk.F[string]("pyc_1234"),
		BeforeID:               sdk.F[string]("pyc_1234"),
		CompensationCurrencies: sdk.F[[]sdk.PublicPayrollCurrency]([]sdk.PublicPayrollCurrency{"USD"}),
		PayFrequencies:         sdk.F[[]sdk.PublicPayFrequency]([]sdk.PublicPayFrequency{"semimonthly"}),
		PaydayBefore:           sdk.F[string]("paydayBefore"),
		PaydayOnOrAfter:        sdk.F[string]("paydayOnOrAfter"),
		PaymentMethods:         sdk.F[[]sdk.PublicPaycheckPaymentMethod]([]sdk.PublicPaycheckPaymentMethod{"direct_deposit"}),
		PayrollIDs:             sdk.F[[]string]([]string{"pay_1234"}),
		PayrollTypes:           sdk.F[[]sdk.PublicPayrollType]([]sdk.PublicPayrollType{"us"}),
		Statuses:               sdk.F[[]sdk.PublicPaycheckStatus]([]sdk.PublicPaycheckStatus{"processing"}),
		WorkerIDs:              sdk.F[[]string]([]string{"wrk_1234"}),
		WorkerTypes:            sdk.F[[]sdk.PayrollListPaychecksParamsWorkerType]([]sdk.PayrollListPaychecksParamsWorkerType{"us_w2"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payroll)
}

func _smokeCase48() {
	payroll, err := client.Payroll.GetPaycheck(context.Background(), "pyc_1234")
	if err != nil {
		panic(err)
	}

	fmt.Println(payroll)
}

func _smokeCase49() {
	timeOff, err := client.TimeOff.ListAssignments(context.Background(), sdk.TimeOffListAssignmentsParams{
		Limit: sdk.F[string]("limit"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(timeOff)
}

func _smokeCase50() {
	timeOff, err := client.TimeOff.ListAssignments(context.Background(), sdk.TimeOffListAssignmentsParams{
		Limit:     sdk.F[string]("limit"),
		AfterID:   sdk.F[string]("wrkasn_1234"),
		BeforeID:  sdk.F[string]("wrkasn_1234"),
		PolicyIDs: sdk.F[[]string]([]string{"top_1234"}),
		WorkerIDs: sdk.F[[]string]([]string{"wrk_1234"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(timeOff)
}

func _smokeCase51() {
	timeOff, err := client.TimeOff.ListBalances(context.Background(), sdk.TimeOffListBalancesParams{
		Limit: sdk.F[string]("limit"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(timeOff)
}

func _smokeCase52() {
	timeOff, err := client.TimeOff.ListBalances(context.Background(), sdk.TimeOffListBalancesParams{
		Limit:     sdk.F[string]("limit"),
		AfterID:   sdk.F[string]("wrkasn_1234"),
		BeforeID:  sdk.F[string]("wrkasn_1234"),
		EndDate:   sdk.F[string]("endDate"),
		PolicyIDs: sdk.F[[]string]([]string{"top_1234"}),
		StartDate: sdk.F[string]("startDate"),
		WorkerIDs: sdk.F[[]string]([]string{"wrk_1234"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(timeOff)
}

func _smokeCase53() {
	timeOff, err := client.TimeOff.ListRequests(context.Background(), sdk.TimeOffListRequestsParams{
		Limit: sdk.F[string]("limit"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(timeOff)
}

func _smokeCase54() {
	timeOff, err := client.TimeOff.ListRequests(context.Background(), sdk.TimeOffListRequestsParams{
		Limit:           sdk.F[string]("limit"),
		AfterID:         sdk.F[string]("afterId"),
		BeforeID:        sdk.F[string]("beforeId"),
		EndsBefore:      sdk.F[string]("endsBefore"),
		EndsOnOrAfter:   sdk.F[string]("endsOnOrAfter"),
		PolicyIDs:       sdk.F[[]string]([]string{"top_1234"}),
		StartsBefore:    sdk.F[string]("startsBefore"),
		StartsOnOrAfter: sdk.F[string]("startsOnOrAfter"),
		Statuses:        sdk.F[[]sdk.TimeOffListRequestsParamsStatus]([]sdk.TimeOffListRequestsParamsStatus{"pending"}),
		WorkerIDs:       sdk.F[[]string]([]string{"wrk_1234"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(timeOff)
}

func _smokeCase55() {
	policy, err := client.TimeOff.Policies.List(context.Background(), sdk.TimeOffPolicyListParams{
		Limit: sdk.F[string]("limit"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(policy)
}

func _smokeCase56() {
	policy, err := client.TimeOff.Policies.List(context.Background(), sdk.TimeOffPolicyListParams{
		Limit:    sdk.F[string]("limit"),
		AfterID:  sdk.F[string]("top_1234"),
		BeforeID: sdk.F[string]("top_1234"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(policy)
}

func _smokeCase57() {
	policy, err := client.TimeOff.Policies.Get(context.Background(), "top_1234")
	if err != nil {
		panic(err)
	}

	fmt.Println(policy)
}

func _smokeCase58() {
	worker, err := client.Workers.List(context.Background(), sdk.WorkerListParams{
		Limit: sdk.F[string]("limit"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(worker)
}

func _smokeCase59() {
	worker, err := client.Workers.List(context.Background(), sdk.WorkerListParams{
		Limit:     sdk.F[string]("limit"),
		AfterID:   sdk.F[string]("wrk_1234"),
		BeforeID:  sdk.F[string]("wrk_1234"),
		Statuses:  sdk.F[[]sdk.WorkerListParamsStatus]([]sdk.WorkerListParamsStatus{"draft"}),
		Types:     sdk.F[[]sdk.WorkerListParamsType]([]sdk.WorkerListParamsType{"employee"}),
		WorkEmail: sdk.F[string]("workEmail"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(worker)
}

func _smokeCase60() {
	worker, err := client.Workers.Get(context.Background(), "wrk_1234")
	if err != nil {
		panic(err)
	}

	fmt.Println(worker)
}

func _smokeCase61() {
	err := client.Workers.Delete(context.Background(), "wrk_1234")
	if err != nil {
		panic(err)
	}
}

func _smokeCase62() {
	worker, err := client.Workers.NewEmployee(context.Background(), sdk.WorkerNewEmployeeParams{
		Compensation: sdk.F[sdk.WorkerNewEmployeeParamsCompensation](sdk.WorkerNewEmployeeParamsCompensation{
			Amount: sdk.F[float64](1),
			Per:    sdk.F[sdk.WorkerNewEmployeeParamsCompensationPer](sdk.WorkerNewEmployeeParamsCompensationPer("hour")),
		}),
		DepartmentID: sdk.F[string]("dpt_1234"),
		Email:        sdk.F[string]("john@joinwarp.com"),
		FirstName:    sdk.F[string]("Jonathan"),
		LastName:     sdk.F[string]("Galt"),
		ManagerID:    sdk.F[string]("wrk_1234"),
		Position:     sdk.F[string]("Software Engineer"),
		StartDate:    sdk.F[string](""),
		WorkLocation: sdk.F[sdk.WorkerNewEmployeeParamsWorkLocationUnion](sdk.WorkerNewEmployeeParamsWorkLocationOfficeWorkLocation{
			Type:        sdk.F[sdk.WorkerNewEmployeeParamsWorkLocationOfficeWorkLocationType](sdk.WorkerNewEmployeeParamsWorkLocationOfficeWorkLocationType("office")),
			WorkplaceID: sdk.F[string]("wkp_1234"),
		}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(worker)
}

func _smokeCase63() {
	worker, err := client.Workers.NewEmployee(context.Background(), sdk.WorkerNewEmployeeParams{
		Compensation: sdk.F[sdk.WorkerNewEmployeeParamsCompensation](sdk.WorkerNewEmployeeParamsCompensation{
			Amount: sdk.F[float64](1),
			Per:    sdk.F[sdk.WorkerNewEmployeeParamsCompensationPer](sdk.WorkerNewEmployeeParamsCompensationPer("hour")),
		}),
		DepartmentID: sdk.F[string]("dpt_1234"),
		Email:        sdk.F[string]("john@joinwarp.com"),
		FirstName:    sdk.F[string]("Jonathan"),
		LastName:     sdk.F[string]("Galt"),
		ManagerID:    sdk.F[string]("wrk_1234"),
		Position:     sdk.F[string]("Software Engineer"),
		StartDate:    sdk.F[string](""),
		WorkLocation: sdk.F[sdk.WorkerNewEmployeeParamsWorkLocationUnion](sdk.WorkerNewEmployeeParamsWorkLocationOfficeWorkLocation{
			Type:        sdk.F[sdk.WorkerNewEmployeeParamsWorkLocationOfficeWorkLocationType](sdk.WorkerNewEmployeeParamsWorkLocationOfficeWorkLocationType("office")),
			WorkplaceID: sdk.F[string]("wkp_1234"),
		}),
		LevelID:           sdk.F[string]("jlvl_1234"),
		PaySchedule:       sdk.F[sdk.WorkerNewEmployeeParamsPaySchedule](sdk.WorkerNewEmployeeParamsPaySchedule("weekly")),
		RequireI9:         sdk.F[bool](false),
		StateRegistration: sdk.F[sdk.WorkerNewEmployeeParamsStateRegistration](sdk.WorkerNewEmployeeParamsStateRegistration("self_managed")),
		StockOptions:      sdk.F[interface{}](0),
		WorkEmail:         sdk.F[string]("john@joinwarp.com"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(worker)
}

func _smokeCase64() {
	worker, err := client.Workers.NewContractor(context.Background(), sdk.WorkerNewContractorParams{
		DepartmentID: sdk.F[string]("dpt_1234"),
		Email:        sdk.F[string]("john@joinwarp.com"),
		EntityType:   sdk.F[sdk.WorkerNewContractorParamsEntityType](sdk.WorkerNewContractorParamsEntityType("individual")),
		FirstName:    sdk.F[string]("Melissa"),
		LastName:     sdk.F[string]("Jones"),
		ManagerID:    sdk.F[string]("wrk_1234"),
		Position:     sdk.F[string]("Design Consultant"),
		StartDate:    sdk.F[string](""),
		WorkCountry:  sdk.F[sdk.WorkerNewContractorParamsWorkCountry](sdk.WorkerNewContractorParamsWorkCountry("AD")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(worker)
}

func _smokeCase65() {
	worker, err := client.Workers.NewContractor(context.Background(), sdk.WorkerNewContractorParams{
		DepartmentID: sdk.F[string]("dpt_1234"),
		Email:        sdk.F[string]("john@joinwarp.com"),
		EntityType:   sdk.F[sdk.WorkerNewContractorParamsEntityType](sdk.WorkerNewContractorParamsEntityType("individual")),
		FirstName:    sdk.F[string]("Melissa"),
		LastName:     sdk.F[string]("Jones"),
		ManagerID:    sdk.F[string]("wrk_1234"),
		Position:     sdk.F[string]("Design Consultant"),
		StartDate:    sdk.F[string](""),
		WorkCountry:  sdk.F[sdk.WorkerNewContractorParamsWorkCountry](sdk.WorkerNewContractorParamsWorkCountry("AD")),
		BusinessName: sdk.F[string]("Galt Enterprises, LLC"),
		Compensation: sdk.F[sdk.WorkerNewContractorParamsCompensation](sdk.WorkerNewContractorParamsCompensation{
			Currency: sdk.F[sdk.WorkerNewContractorParamsCompensationCurrency](sdk.WorkerNewContractorParamsCompensationCurrency("USD")),
			Amount:   sdk.F[float64](1),
			Per:      sdk.F[sdk.WorkerNewContractorParamsCompensationPer](sdk.WorkerNewContractorParamsCompensationPer("year")),
		}),
		LevelID:     sdk.F[string]("jlvl_1234"),
		PaySchedule: sdk.F[sdk.WorkerNewContractorParamsPaySchedule](sdk.WorkerNewContractorParamsPaySchedule("weekly")),
		ScopeOfWork: sdk.F[string](""),
		WorkEmail:   sdk.F[string]("john@joinwarp.com"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(worker)
}

func _smokeCase66() {
	worker, err := client.Workers.Invite(context.Background(), "wrk_1234")
	if err != nil {
		panic(err)
	}

	fmt.Println(worker)
}

func _smokeCase67() {
	worker, err := client.Workers.RevealSsn(context.Background(), sdk.WorkerRevealSsnParams{
		WorkerIDs: sdk.F[[]string]([]string{"wrk_khac8380c2Lm", "wrk_q7Vm2pR9xK4c"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(worker)
}

func _smokeCase68() {
	workplace, err := client.Workplaces.List(context.Background(), sdk.WorkplaceListParams{
		Limit: sdk.F[string]("limit"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(workplace)
}

func _smokeCase69() {
	workplace, err := client.Workplaces.List(context.Background(), sdk.WorkplaceListParams{
		Limit:    sdk.F[string]("limit"),
		AfterID:  sdk.F[string]("wkp_1234"),
		BeforeID: sdk.F[string]("wkp_1234"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(workplace)
}

func _smokeCase70() {
	workplace, err := client.Workplaces.New(context.Background(), sdk.WorkplaceNewParams{
		Address: sdk.F[sdk.WorkplaceNewParamsAddress](sdk.WorkplaceNewParamsAddress{
			Line1:      sdk.F[string]("x"),
			City:       sdk.F[string](""),
			PostalCode: sdk.F[string](""),
			State:      sdk.F[sdk.WorkplaceNewParamsAddressState](sdk.WorkplaceNewParamsAddressState("AL")),
			Country:    sdk.F[sdk.WorkplaceNewParamsAddressCountry](sdk.WorkplaceNewParamsAddressCountry("US")),
		}),
		Name: sdk.F[string]("x"),
		Type: sdk.F[sdk.WorkplaceNewParamsType](sdk.WorkplaceNewParamsType("remote")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(workplace)
}

func _smokeCase71() {
	workplace, err := client.Workplaces.Update(context.Background(), "wkp_1234", sdk.WorkplaceUpdateParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(workplace)
}

func _smokeCase72() {
	workplace, err := client.Workplaces.Update(context.Background(), "wkp_1234", sdk.WorkplaceUpdateParams{
		Name: sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(workplace)
}

var cases = []smokeCase{
	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/benefits/health_plans",
		Label:     "required params",
		Run:       _smokeCase0,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/benefits/health_plans",
		Label:     "all params",
		Run:       _smokeCase1,
	},

	{
		Operation: "get",
		Method:    "GET",
		Path:      "/v1/benefits/health_plans/{id}",
		Run:       _smokeCase2,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/benefits/retirement_plans",
		Label:     "required params",
		Run:       _smokeCase3,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/benefits/retirement_plans",
		Label:     "all params",
		Run:       _smokeCase4,
	},

	{
		Operation: "get",
		Method:    "GET",
		Path:      "/v1/benefits/retirement_plans/{id}",
		Run:       _smokeCase5,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/benefits/deductions",
		Label:     "required params",
		Run:       _smokeCase6,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/benefits/deductions",
		Label:     "all params",
		Run:       _smokeCase7,
	},

	{
		Operation: "get",
		Method:    "GET",
		Path:      "/v1/benefits/deductions/{id}",
		Run:       _smokeCase8,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/custom_fields",
		Run:       _smokeCase9,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/custom_fields",
		Label:     "required params",
		Run:       _smokeCase10,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/custom_fields",
		Label:     "all params",
		Run:       _smokeCase11,
	},

	{
		Operation: "get",
		Method:    "GET",
		Path:      "/v1/custom_fields/{id}",
		Run:       _smokeCase12,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/custom_fields/{id}",
		Label:     "required params",
		Run:       _smokeCase13,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/custom_fields/{id}",
		Label:     "all params",
		Run:       _smokeCase14,
	},

	{
		Operation: "archive",
		Method:    "POST",
		Path:      "/v1/custom_fields/{id}/archive",
		Run:       _smokeCase15,
	},

	{
		Operation: "createOption",
		Method:    "POST",
		Path:      "/v1/custom_fields/{id}/options",
		Label:     "required params",
		Run:       _smokeCase16,
	},

	{
		Operation: "createOption",
		Method:    "POST",
		Path:      "/v1/custom_fields/{id}/options",
		Label:     "all params",
		Run:       _smokeCase17,
	},

	{
		Operation: "updateOption",
		Method:    "PATCH",
		Path:      "/v1/custom_field_options/{id}",
		Label:     "required params",
		Run:       _smokeCase18,
	},

	{
		Operation: "updateOption",
		Method:    "PATCH",
		Path:      "/v1/custom_field_options/{id}",
		Label:     "all params",
		Run:       _smokeCase19,
	},

	{
		Operation: "deleteOption",
		Method:    "DELETE",
		Path:      "/v1/custom_field_options/{id}",
		Run:       _smokeCase20,
	},

	{
		Operation: "archiveOption",
		Method:    "POST",
		Path:      "/v1/custom_field_options/{id}/archive",
		Run:       _smokeCase21,
	},

	{
		Operation: "listValues",
		Method:    "GET",
		Path:      "/v1/custom_field_values",
		Label:     "required params",
		Run:       _smokeCase22,
	},

	{
		Operation: "listValues",
		Method:    "GET",
		Path:      "/v1/custom_field_values",
		Label:     "all params",
		Run:       _smokeCase23,
	},

	{
		Operation: "upsertValue",
		Method:    "PUT",
		Path:      "/v1/custom_field_values",
		Run:       _smokeCase24,
	},

	{
		Operation: "clearValue",
		Method:    "DELETE",
		Path:      "/v1/custom_field_values",
		Run:       _smokeCase25,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/departments",
		Label:     "required params",
		Run:       _smokeCase26,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/departments",
		Label:     "all params",
		Run:       _smokeCase27,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/departments",
		Run:       _smokeCase28,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/departments/{id}",
		Label:     "required params",
		Run:       _smokeCase29,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/departments/{id}",
		Label:     "all params",
		Run:       _smokeCase30,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/levels",
		Run:       _smokeCase31,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/offers",
		Label:     "required params",
		Run:       _smokeCase32,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/offers",
		Label:     "all params",
		Run:       _smokeCase33,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/offers",
		Label:     "required params",
		Run:       _smokeCase34,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/offers",
		Label:     "all params",
		Run:       _smokeCase35,
	},

	{
		Operation: "void",
		Method:    "POST",
		Path:      "/v1/offers/{id}/void",
		Label:     "required params",
		Run:       _smokeCase36,
	},

	{
		Operation: "void",
		Method:    "POST",
		Path:      "/v1/offers/{id}/void",
		Label:     "all params",
		Run:       _smokeCase37,
	},

	{
		Operation: "extendDeadline",
		Method:    "POST",
		Path:      "/v1/offers/{id}/extend-deadline",
		Run:       _smokeCase38,
	},

	{
		Operation: "resend",
		Method:    "POST",
		Path:      "/v1/offers/{id}/resend",
		Run:       _smokeCase39,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/pay_rates",
		Label:     "required params",
		Run:       _smokeCase40,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/pay_rates",
		Label:     "all params",
		Run:       _smokeCase41,
	},

	{
		Operation: "get",
		Method:    "GET",
		Path:      "/v1/pay_rates/{id}",
		Run:       _smokeCase42,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/payrolls",
		Label:     "required params",
		Run:       _smokeCase43,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/payrolls",
		Label:     "all params",
		Run:       _smokeCase44,
	},

	{
		Operation: "get",
		Method:    "GET",
		Path:      "/v1/payrolls/{id}",
		Run:       _smokeCase45,
	},

	{
		Operation: "listPaychecks",
		Method:    "GET",
		Path:      "/v1/paychecks",
		Label:     "required params",
		Run:       _smokeCase46,
	},

	{
		Operation: "listPaychecks",
		Method:    "GET",
		Path:      "/v1/paychecks",
		Label:     "all params",
		Run:       _smokeCase47,
	},

	{
		Operation: "getPaycheck",
		Method:    "GET",
		Path:      "/v1/paychecks/{id}",
		Run:       _smokeCase48,
	},

	{
		Operation: "listAssignments",
		Method:    "GET",
		Path:      "/v1/time_off/assignments",
		Label:     "required params",
		Run:       _smokeCase49,
	},

	{
		Operation: "listAssignments",
		Method:    "GET",
		Path:      "/v1/time_off/assignments",
		Label:     "all params",
		Run:       _smokeCase50,
	},

	{
		Operation: "listBalances",
		Method:    "GET",
		Path:      "/v1/time_off/balances",
		Label:     "required params",
		Run:       _smokeCase51,
	},

	{
		Operation: "listBalances",
		Method:    "GET",
		Path:      "/v1/time_off/balances",
		Label:     "all params",
		Run:       _smokeCase52,
	},

	{
		Operation: "listRequests",
		Method:    "GET",
		Path:      "/v1/time_off/requests",
		Label:     "required params",
		Run:       _smokeCase53,
	},

	{
		Operation: "listRequests",
		Method:    "GET",
		Path:      "/v1/time_off/requests",
		Label:     "all params",
		Run:       _smokeCase54,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/time_off/policies",
		Label:     "required params",
		Run:       _smokeCase55,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/time_off/policies",
		Label:     "all params",
		Run:       _smokeCase56,
	},

	{
		Operation: "get",
		Method:    "GET",
		Path:      "/v1/time_off/policies/{id}",
		Run:       _smokeCase57,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/workers",
		Label:     "required params",
		Run:       _smokeCase58,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/workers",
		Label:     "all params",
		Run:       _smokeCase59,
	},

	{
		Operation: "get",
		Method:    "GET",
		Path:      "/v1/workers/{id}",
		Run:       _smokeCase60,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/workers/{id}",
		Run:       _smokeCase61,
	},

	{
		Operation: "createEmployee",
		Method:    "POST",
		Path:      "/v1/workers/employee",
		Label:     "required params",
		Run:       _smokeCase62,
	},

	{
		Operation: "createEmployee",
		Method:    "POST",
		Path:      "/v1/workers/employee",
		Label:     "all params",
		Run:       _smokeCase63,
	},

	{
		Operation: "createContractor",
		Method:    "POST",
		Path:      "/v1/workers/contractor",
		Label:     "required params",
		Run:       _smokeCase64,
	},

	{
		Operation: "createContractor",
		Method:    "POST",
		Path:      "/v1/workers/contractor",
		Label:     "all params",
		Run:       _smokeCase65,
	},

	{
		Operation: "invite",
		Method:    "POST",
		Path:      "/v1/workers/{id}/invite",
		Run:       _smokeCase66,
	},

	{
		Operation: "revealSsn",
		Method:    "POST",
		Path:      "/v1/workers/reveal_ssn",
		Run:       _smokeCase67,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/workplaces",
		Label:     "required params",
		Run:       _smokeCase68,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/workplaces",
		Label:     "all params",
		Run:       _smokeCase69,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/workplaces",
		Run:       _smokeCase70,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/workplaces/{id}",
		Label:     "required params",
		Run:       _smokeCase71,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/workplaces/{id}",
		Label:     "all params",
		Run:       _smokeCase72,
	},
}

func selectedCases() []smokeCase {
	filter := os.Getenv("SCALAR_SMOKE_FILTER")
	if filter == "" {
		return cases
	}
	needles := strings.Split(filter, ",")
	selected := make([]smokeCase, 0, len(cases))
	for _, testCase := range cases {
		for _, needle := range needles {
			needle = strings.TrimSpace(needle)
			if needle == "" {
				continue
			}
			if strings.Contains(testCase.Operation, needle) || strings.Contains(testCase.Path, needle) {
				selected = append(selected, testCase)
				break
			}
		}
	}
	return selected
}

// How many cases run at once. A large SDK has hundreds of operations, and one goroutine per case
// puts more requests in flight than the client's transport pools connections for. SCALAR_SMOKE_CONCURRENCY
// overrides the cap; anything unparseable falls back to the default.
func smokeConcurrency(caseCount int) int {
	limit := 32
	if override, err := strconv.Atoi(os.Getenv("SCALAR_SMOKE_CONCURRENCY")); err == nil && override > 0 {
		limit = override
	}
	if caseCount < limit {
		return caseCount
	}
	return limit
}

func runCase(testCase smokeCase) (result smokeResult) {
	startedAt := time.Now()
	result = smokeResult{
		Operation: testCase.Operation,
		Method:    testCase.Method,
		Path:      testCase.Path,
		Label:     testCase.Label,
		Status:    "passed",
	}
	defer func() {
		result.DurationMs = time.Since(startedAt).Milliseconds()
		if recovered := recover(); recovered != nil {
			result.Status = "failed"
			result.Error = fmt.Sprint(recovered)
		}
	}()
	testCase.Run()
	return result
}

func main() {
	selected := selectedCases()
	results := make([]smokeResult, len(selected))
	var wg sync.WaitGroup
	// Buffered channel as a counting semaphore: every goroutine still starts, but only
	// smokeConcurrency of them hold a slot — and so have a request in flight — at a time.
	semaphore := make(chan struct{}, smokeConcurrency(len(selected)))
	for index, testCase := range selected {
		wg.Add(1)
		go func(index int, testCase smokeCase) {
			defer wg.Done()
			semaphore <- struct{}{}
			defer func() { <-semaphore }()
			results[index] = runCase(testCase)
		}(index, testCase)
	}
	wg.Wait()

	failed := 0
	for _, result := range results {
		if result.Status == "failed" {
			failed++
		}
	}

	report := map[string]interface{}{"total": len(results), "failed": failed, "results": results}
	if reportPath := os.Getenv("SCALAR_SMOKE_REPORT"); reportPath != "" {
		bytes, err := json.Marshal(report)
		if err != nil {
			panic(err)
		}
		if err := os.WriteFile(reportPath, bytes, 0o644); err != nil {
			panic(err)
		}
	} else {
		for _, result := range results {
			suffix := ""
			if result.Label != "" {
				suffix = " [" + result.Label + "]"
			}
			if result.Status == "passed" {
				fmt.Printf("PASS %s%s (%s %s) %dms\n", result.Operation, suffix, result.Method, result.Path, result.DurationMs)
			} else {
				fmt.Fprintf(os.Stderr, "FAIL %s%s (%s %s)\n%s\n", result.Operation, suffix, result.Method, result.Path, result.Error)
			}
		}
		if len(results) == 0 {
			fmt.Fprintln(os.Stderr, "No code samples ran (empty SDK or a SCALAR_SMOKE_FILTER that matched nothing).")
		} else {
			fmt.Printf("\n%d/%d samples passed\n", len(results)-failed, len(results))
		}
	}

	if failed > 0 || len(results) == 0 {
		os.Exit(1)
	}
}
